### ISSUE TITLE
User register server validation errors are not displayed next to the field

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#122]
__Description__

Server validation errors are displayed beneath the submit-button, rather than next to the field that has the error making it very unclear what went wrong (see screenshot). This issue concerns the validation "email has already been taken", but it seems like its a general problem..

__Severity__: Broken styling / Confusing

__URL__: http://justarrived.dev-machine.com/#/user/register

__Error message__: "has already been taken"

__Role__: Not logged in

__How to recreate it__

1. Goto register new user
2. Fill in valid details, but with an email address that already exists in the system
3. Submit the form

__Expected outcome__: Validation error displayed directly beneath the field that has the validation error.

__Screenshot__

<img width="542" alt="screen shot 2016-05-07 at 15 37 49" src="https://cloud.githubusercontent.com/assets/922411/15092493/ea56ae76-146b-11e6-8dd8-957aa3b2e713.png">

**Comment by ti-sedp** [comment]
Fixed  API error style sheet

![2559-05-08_22h47_06](https://cloud.githubusercontent.com/assets/16758634/15098760/e41deff2-156e-11e6-8e82-2e1fa90a6ca9.png)

**Comment by buren** [comment]
Potentially closed by #194

**Comment by Ubonrat** [comment]
Fixed.
