### ISSUE TITLE
Add Google Maps API key

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#124]
We must add a valid Google Maps API key to the frontend otherwise Google will throttle us a lot more and we risk that our quota is existed, thus breaking all maps within the app.

The API key must be created/provided by @FivelFred and it should limit the domains it can be used on to  dev-machine.com and *.justarrived.se. @FivelFred feel free to ask for help creating the key.

After the key is created we should add it to a config file, so its easy to update.

**Comment by ti-sedp** [comment]
Fixed
Add google map api key in config file "google_map_api_key"
