### ISSUE TITLE
Unnecessary loading of languages on create user profile

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#126]
__Description__

Every time the "LANGUAGE SKILLS*" field is clicked `/api/v1/languages?filter[name]=` is fetched causing unnecessary wait for the user and extra load on the server. Should only be requested if the user types something

__Severity__: Enhancement

__URL__: http://justarrived.dev-machine.com/#/user

__Error message__: None

__Role__: User

__How to recreate it__

1. Register a new user
2. On the next page click the "Language skill" field
3. The frontend requests `/api/v1/languages?filter[name]=`

__Expected outcome__: Frontend only requests when the user has typed something.

__Screenshot__

<img width="1201" alt="screen shot 2016-05-07 at 16 14 29" src="https://cloud.githubusercontent.com/assets/922411/15092599/d1755832-146e-11e6-8c7a-3e8c8724c382.png">

**Comment by ti-sedp** [comment]
Fixed
Empty query search text not call api
