### ISSUE TITLE
Can't continue from create user profile view

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#127]
__Description__

Can't continue from the create profile view even though successful `PATCH` requests are sent and returned with a 200 ok status, the frontend does not "redirect" the user to the next view.

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/user

__Error message__: None

__Role__: User

__How to recreate it__

1. Register a new user
2. Fill in required fields on "Create profile" page
3. Click "Fortsätt"

__Expected outcome__: Redirected to the next page.

__System__: OSX

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

<img width="555" alt="screen shot 2016-05-07 at 16 18 08" src="https://cloud.githubusercontent.com/assets/922411/15092620/541d02c6-146f-11e6-8817-a32ddcec0072.png">

**Comment by ti-sedp** [comment]
Please check this one
1. Register new arriver user
2. Fill in user profile
3. i should be redirect to confirmed page

![2559-05-08_21h32_55](https://cloud.githubusercontent.com/assets/16758634/15098311/707a4460-1564-11e6-8f4d-da28ae301369.png)

**Comment by buren** [comment]
@ti-sedp confirmed 👍
