### ISSUE TITLE
Mixed translations on Create user profile view

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#128]
__Description__

Mixed translations on create user profile view. Even though I've chosen "en" some content is displayed in Swedish.

__Severity__: Wrong translation

__URL__: http://justarrived.dev-machine.com/#/user

__Role__: User

__How to recreate it__

1. Chose "en" locale
2. Register new user
3. The next page will display mixed content

__Expected outcome__: All strings in English.

__Screenshot__

<img width="555" alt="screen shot 2016-05-07 at 16 18 08" src="https://cloud.githubusercontent.com/assets/922411/15092636/fb685f62-146f-11e6-9c86-10473469f010.png">

**Comment by chris-sedp** [comment]
Fixed. Will be deployed later together with the other translation issues
