### ISSUE TITLE
Unused field on Create user profile view

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#129]
__Description__

The field "Competences" on the create user profile view is not submitted to the API and should be removed.

__Severity__: Bad UX

__URL__: http://justarrived.dev-machine.com/#/user

__Error message__: None

__Role__: User

__How to recreate it__

1. Register new user
2. On create profile view page the extra field is displayed

__Screenshot__

<img width="459" alt="screen shot 2016-05-07 at 16 24 49" src="https://cloud.githubusercontent.com/assets/922411/15092655/7e714ad6-1470-11e6-8e03-c1e0700accf1.png">

**Comment by FivelFred** [comment]
Is this not in place in the back-end @buren ?

**Comment by buren** [comment]
@FivelFred well it depends.. I have implemented `Skill`s, but there is no free-form text field for `competences`, there is `description`, `job_experience` and `education` text fields.

It wouldn't take me more than 15 min to add support for a text field `competences` if thats what we want.

**Comment by buren** [comment]
@FivelFred should I add this in the API as a free-text field or what should we do?

**Comment by ti-sedp** [comment]
Fixed
![2559-05-09_09h47_33](https://cloud.githubusercontent.com/assets/16758634/15102556/16b53842-15cb-11e6-95d2-31c414392ec3.png)

**Comment by FivelFred** [comment]
I belive Ti just removed this from the front-end so maybe we'll add this after the bash


Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Jacob Burenstam <notifications@github.com> 
Datum: 05-08-2016  23:07  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Unused field on Create user
  profile view (#129) 

@FivelFred should I add this in the API as a free-text field or what should we do?
