### ISSUE TITLE
Create comment is "spammable"

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#132]
__Description__

The job comment field is "spammable" in the sense that if the user fills in a comment and then hits ENTER a few times in a row, the comment is submitted to the API multiple times.. Instead the field should be cleared instantly while the comment is being submitted to the API.

__Severity__: Enhancement

__URL__: http://justarrived.dev-machine.com/#/jobs/:id

__Role__: User

__How to recreate it__

1. Login as any user
2. Goto to a job page
3. Fill in a comment
4. Hit the ENTER-key a few times in a row

__Expected outcome__: Only one comment is submitted

__Screenshot__

<img width="466" alt="screen shot 2016-05-07 at 17 03 45" src="https://cloud.githubusercontent.com/assets/922411/15092830/b03b7168-1475-11e6-8e92-5dc5f61aec60.png">

**Comment by ti-sedp** [comment]
Fixed in job detail, my assignment (both company and arreiver)

**Comment by buren** [comment]
Potentially closed by #201

**Comment by buren** [comment]
Its __a lot better__ but not completely fixed.. closing this since I deem this "good enough"
