### ISSUE TITLE
Broken link, "Review", on job show page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#133]
__Description__

There is a link "Review" on the job page which links to an empty page.

__Severity__: Bad UX

__URL__: http://justarrived.dev-machine.com/#/jobs/:id

__How to recreate it__

1. Goto job show page

__Screenshot__

<img width="466" alt="screen shot 2016-05-07 at 17 04 38" src="https://cloud.githubusercontent.com/assets/922411/15092841/fef5b9ee-1475-11e6-8c4e-4255320a543e.png">

**Comment by FivelFred** [comment]
The wording will also need to be adjusted by translator

**Comment by FivelFred** [comment]
See #248
