### ISSUE TITLE
Mixed translations on job show page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#134]
__Description__

Mixed content on job show page. Even though English has been chosen there is content in Swedish..

__Severity__: Wrong translation

__URL__: http://justarrived.dev-machine.com/#/jobs/:id

__Expected outcome__: Content in only one language

__Screenshot__

See "Timmar" etc.

<img width="492" alt="screen shot 2016-05-07 at 17 07 03" src="https://cloud.githubusercontent.com/assets/922411/15092856/61852a36-1476-11e6-9372-665066fbe2cc.png">

**Comment by Ubonrat** [comment]
Fixed.
