### ISSUE TITLE
Misleading button title for regular user on job show page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#135]
__Description__

When logged in as a regular, non-company, user the button on the bottom says "Search assignments", however when clicking the button the user actually applies to the job. 

__Severity__: Confusing / Misleading

__URL__: http://justarrived.dev-machine.com/#/jobs/:id

__Role__: User

__How to recreate it__

1. Login in as a regular, non-company, user
2. Goto to a job page

__Screenshot__

<img width="495" alt="screen shot 2016-05-07 at 18 12 44" src="https://cloud.githubusercontent.com/assets/922411/15093186/150e59d4-1480-11e6-950a-4a987af48823.png">

**Comment by buren** [comment]
This is actually a bad translation.. in Swedish this is "Sök uppdrag" which has been literally translated to English "Search assignment", while in this context the correct translation would be "Apply for assignment" . Also I don't think "assignment" is that good I think "job" is a lot better/clearer.

@FivelFred the above is a __great__ example of why translations can be so tricky and often are very dependent on context.

Lastly @FivelFred what do you think about "assignment"?

**Comment by FivelFred** [comment]
@buren You are perfectly right. The translators will get the chance to go through the application in the beginning of next week to review their translations contextually. This kind of things will then be resolved. It is of importance that the languages are added and the bugs are resolved in order for this to be fruitful. So we are dependent on SEDP to deliver.

**Comment by Ubonrat** [comment]
Fixed.
