### ISSUE TITLE
Apply for job button is shown even though the user has already applied

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#136]
__Description__

Even though the user has applied for a job the apply-button (that currently has the wrong text..) is shown. Also if the user clicks the button there is no visible error message even though the backend returns a 422 status that the user has already applied to the job.. Meaning that the user will not be taken anywhere and it will look like the button just doesn't work..

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/jobs/:id

__Error message__: No error message (thats the problem...)

__Role__: Company user / user / Not logged in

__How to recreate it__

1. Goto ...
2. Click ...
3.

__Expected outcome__

Either no button should be shown or an error message should be displayed to the user, stating that they've already applied for it..

__Screenshot__

<img width="1264" alt="screen shot 2016-05-07 at 18 24 12" src="https://cloud.githubusercontent.com/assets/922411/15093220/efbbf64a-1480-11e6-8702-ee35d20e9992.png">

**Comment by ti-sedp** [comment]
Hide apply job button if arriver user take it alrady

**Comment by buren** [comment]
@ti-sedp is this fixed? :)
