### ISSUE TITLE
Frontend doesn't send X-API-LOCALE header even though the user has changed locale

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#137]
__Description__

Even though a user has explicitly changed locale the frontend doesn't send the `X-API-LOCALE` header to the backend, causing the backend to always return the users default locale rather than their current setting.

__Severity__: Wrong translation

__URL__: *

__How to recreate it__

1. Create a user with the primary language Swedish
2. Change the locale to English
3. The header `X-API-LOCALE` is *not* sent to the backend

__Expected outcome__: The frontend sends the header to the API

__Screenshot__

<img width="1264" alt="screen shot 2016-05-07 at 18 24 12" src="https://cloud.githubusercontent.com/assets/922411/15093232/69ba5c70-1481-11e6-8db8-5465268fdd4e.png">

**Comment by ti-sedp** [comment]
Fixed on github
![2559-05-09_19h36_50](https://cloud.githubusercontent.com/assets/16758634/15113330/c1437344-161d-11e6-8e05-76c2965e300d.png)
![2559-05-09_19h36_50](https://cloud.githubusercontent.com/assets/16758634/15113331/c3a0cf9c-161d-11e6-9b96-a5c3b3ba6993.png)
