### ISSUE TITLE
Google Maps doesn't center correctly on jobs listing page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#138]
__Description__

On the jobs listings page the map doesn't center around the job locations correctly. Even though there are jobs in both in Denmark and Stockholm (on staging) the map always centers around the job in Denmark.

__Severity__: Broken styling

__URL__: http://justarrived.dev-machine.com/#/jobs

__How to recreate it__

1. Navigate to the jobs listing page

__Expected outcome__

The maps centers around all locations, if locations are far apart it should zoom out and show them all..

__Screenshot__

<img width="494" alt="screen shot 2016-05-07 at 18 38 06" src="https://cloud.githubusercontent.com/assets/922411/15093282/e13de608-1482-11e6-868a-8d44719b9486.png">

**Comment by buren** [comment]
It seems like it centers around the location of the job created most recently.

**Comment by ti-sedp** [comment]
Fixed 
![2559-05-09_11h06_43](https://cloud.githubusercontent.com/assets/16758634/15103495/301df1ce-15d6-11e6-82c0-7a96bc62af3f.png)

**Comment by buren** [comment]
Closed by #205
