### ISSUE TITLE
Google Maps broken fullscreen view

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#139]
__Description__

When clicking the ➕ icon on the Google Map it doesn't properly fill out the entire screen (see screenshot). 

__Severity__: Broken styling

__URL__: http://justarrived.dev-machine.com/#/jobs

__Browser__: Chrome (OSX)

__Screenshot__

<img width="500" alt="screen shot 2016-05-07 at 18 39 58" src="https://cloud.githubusercontent.com/assets/922411/15093290/4772cd9e-1483-11e6-8d86-a9f153fb7be8.png">

**Comment by ti-sedp** [comment]
Fixed
Call google api event resize and fitBounds after zoom button click
