### ISSUE TITLE
Company user can't rate user

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#140]
__Description__

Currently it doesn't seem possible to rate a user even though an invoice has been created

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/company/jobs

__Error message__: None

__Role__: Company user

__How to recreate it__

1. Create job
2. User apply for job
3. Company user accept user
4. User confirm acceptance
5. Company user create invoice
6. Company user go to http://justarrived.dev-machine.com/#/company/jobs
7. Try to click on the "stars" to give a rating
8. Nothing happens..

__Expected outcome__: Company user rates the user

__Screenshot__

<img width="440" alt="screen shot 2016-05-07 at 18 51 29" src="https://cloud.githubusercontent.com/assets/922411/15093665/7eba9416-148e-11e6-9791-3b256c2d3693.png">

**Comment by ti-sedp** [comment]
pagaende uppdrag show (will-perform:true)
senaste akivitet shoe (accepted:false)
saknar bedomning (performed:true)

arkiv : show job that has an invoice
