### ISSUE TITLE
Broken styling for hourly rate when creating a job

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#141]
__Description__

When creating a hob the hourly rate select menu looks broken

__Severity__: Broken styling

__URL__: http://justarrived.dev-machine.com/#/job/create

__How to recreate it__

1. Goto http://justarrived.dev-machine.com/#/job/create

__System__: OSX

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

<img width="395" alt="screen shot 2016-05-07 at 20 03 52" src="https://cloud.githubusercontent.com/assets/922411/15093684/0c229268-148f-11e6-96a4-6d3420eb8d35.png">

**Comment by Ubonrat** [comment]
Fixed.
