### ISSUE TITLE
Missing translation on job approved page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#142]
__Severity__: Missing translation

__URL__: http://justarrived.dev-machine.com/#/job/approved

__Role__: Company user

__How to recreate it__

1. Login as company user
2. Create a new job
3. Approve/confirm job

__Expected outcome__: Page with complete translations.

__Screenshot__

<img width="428" alt="screen shot 2016-05-07 at 20 08 43" src="https://cloud.githubusercontent.com/assets/922411/15093699/c95ebd34-148f-11e6-923f-57e45e87dd3e.png">

**Comment by Ubonrat** [comment]
Fixed.
