### ISSUE TITLE
Hard coded user chat on company job page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#144]
__Description__

On the company job page the number of comments is hardcoded to always be "Två kommentarer", so it shows the wrong information and the translation is missing.

__Severity__: Incorrect information

__URL__: http://justarrived.dev-machine.com/#/company/job/:id

__Role__: Company user

__How to recreate it__

1. Create a job
2. Goto to "My assignment"
3. Click on a created job

__Expected outcome__: The correct chat is shown (if any)

__Screenshot__

<img width="440" alt="screen shot 2016-05-07 at 20 16 50" src="https://cloud.githubusercontent.com/assets/922411/15093737/b175750e-1490-11e6-89a5-bcfe4432ace5.png">

**Comment by buren** [comment]
Relevant code https://github.com/justarrived/just-match-frontend/blob/da8c88bc47d00d155a77d773486afed7755a8dd2/src/app/common/templates/company-job.html#L42

**Comment by ti-sedp** [comment]
Fixed 144
![2559-05-09_02h42_14](https://cloud.githubusercontent.com/assets/16758634/15099977/b55cfd86-158f-11e6-95d9-e207eb1cc825.png)
