### ISSUE TITLE
When a user applies the wrong copy is shown

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#145]
__Description__

When a user applies for a job the feedback messages states (paraphrased):

> An account has been created and you've applied for your first assignment
> When your email is confirmed the assignment will be created

The information is not only wrong but also a mix between applying for a job (regular user) and creating one (company user).

__Severity__: Wrong information / feedback

__URL__: http://justarrived.dev-machine.com/#/job/accept

__Role__: User

__How to recreate it__

1. Login in as regular user
2. Goto a job page
3. Apply or job

__Expected outcome__: A message stating that the user has applied for a job and that they'll receive an email/notification if they're accepted by the job creator.

__Screenshot__

<img width="546" alt="screen shot 2016-05-07 at 20 23 33" src="https://cloud.githubusercontent.com/assets/922411/15093773/997aa4dc-1491-11e6-9fd7-a637caec519a.png">

**Comment by Ubonrat** [comment]
Fixed.
