### ISSUE TITLE
Job filter on job listings page doesn't work

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#146]
__Description__

The dropdown menu displayed at the top of the job listings page doesn't do anything. 

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/jobs

__How to recreate it__

1. Goto http://justarrived.dev-machine.com/#/jobs
2. Click and select something from the dropdown menu

__Expected outcome__: Jobs are filterable by chosen value (now it just logs the selected value to the console)

__Screenshot__

<img width="541" alt="screen shot 2016-05-07 at 20 27 33" src="https://cloud.githubusercontent.com/assets/922411/15093798/295bebd8-1492-11e6-9125-1b8dca0abf5b.png">

**Comment by buren** [comment]
My suggestion is that we remove that select box all together, since the categories aren't translated and there are more than 8000 (!) of them. @FivelFred is this something you've discussed?

**Comment by chris-sedp** [comment]
Sounds like a good idea. If we gonna keep it it would be good to have a filter on the jobs route.

**Comment by buren** [comment]
@chris-sedp we wont filter on category, there are just waaay to many of them (over 8000), if we're gonna have filters etc, I would say that `job_date`/`hours`/`hourly_pay` would be more useful.

In other words for the MVP we can just remove the above dropdown and we'l add new filter later on.

**Comment by FivelFred** [comment]
Agree

**Comment by ti-sedp** [comment]
Fixed remove category selectbox
