### ISSUE TITLE
Missing "close" icon in chose language menu

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#147]
__Description__

There is no close icon in the chose language menu, the only way to close it is to click a language.

__Severity__: Bad UX

__URL__: *

__How to recreate it__

1. Click the locale/language icon in the navbar

__Expected outcome__

A "close" icon is shown in the top right corner (just like in the "Menu")

__Screenshot__

<img width="540" alt="screen shot 2016-05-07 at 20 29 25" src="https://cloud.githubusercontent.com/assets/922411/15093811/a49bfb62-1492-11e6-815f-d819b53f75ab.png">

**Comment by Ubonrat** [comment]
Close button has been added.
