### ISSUE TITLE
Hard coded (?) rating on chose candidate page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#148]
__Description__

Users average rating is hard coded (?) or at least there is a rounding issue.

__Severity__: Wrong information / Hard coded data

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidates

__How to recreate it__

1. Login in as company user
2. Goto job that has candidates
3. Click "Chose candidate"

__Expected outcome__

The correct average rating is shown.

__Screenshot__
<img width="438" alt="screen shot 2016-05-07 at 20 34 10" src="https://cloud.githubusercontent.com/assets/922411/15093846/7a81989a-1493-11e6-9d6f-548f7d0d1e9b.png">

**Comment by buren** [comment]
The average rating of the above referenced user is 3.8, however the view shows 3 stars so either its hard coded or there is a rounding issue.

**Comment by chris-sedp** [comment]
We will have a look at this one. We round it to an integer right now but seems like its not working. We don't have half stars either. We will check how we can make this more precise.

**Comment by ti-sedp** [comment]
Fixed: use image background instead html special character

![2559-05-09_02h45_44](https://cloud.githubusercontent.com/assets/16758634/15099997/41a542ee-1590-11e6-911e-cea765ccc7fc.png)
