### ISSUE TITLE
Hard coded number of jobs on chose candidate page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#149]
__Description__

Users total number of performed jobs is hard coded.

__Severity__: Wrong information / Hard coded data

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidates

__How to recreate it__

1. Login in as company user
2. Goto job that has candidates
3. Click "Chose candidate"

__Expected outcome__

The correct total number of jobs is displayed.

__Screenshot__
<img width="438" alt="screen shot 2016-05-07 at 20 34 10" src="https://cloud.githubusercontent.com/assets/922411/15093846/7a81989a-1493-11e6-9d6f-548f7d0d1e9b.png">

**Comment by ti-sedp** [comment]
Get will-perform uppdrag from user-jobs
![2559-05-09_02h56_46](https://cloud.githubusercontent.com/assets/16758634/15100067/e1a1a89a-1591-11e6-9a2c-a35cab50b451.png)
