### ISSUE TITLE
Unimplemented feature "Favourite" on chose candidate page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#150]
__Description__

An unimplemented feature "Favourite" is displayed.

__Severity__: Misleading 

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidates

__How to recreate it__

1. Login in as company user
2. Goto job that has candidates
3. Click "Chose candidate"

__Expected outcome__

No "Favourite" text or icon is displayed.

__Screenshot__
<img width="438" alt="screen shot 2016-05-07 at 20 34 10" src="https://cloud.githubusercontent.com/assets/922411/15093846/7a81989a-1493-11e6-9d6f-548f7d0d1e9b.png">

**Comment by FivelFred** [comment]
Second on this

**Comment by buren** [comment]
Closed by #187
