### ISSUE TITLE
Missing content/translation on chose candidate page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#151]
__Description__

There is still "Lorem ipsum" content..

__Severity__: Broken styling / Wrong translation

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidates

__Role__: Company user

__How to recreate it__

1. Login in as company user
2. Goto a job with candidates
3. Click "Chose candidate"

__Expected outcome__: Only "real" content is displayed.

__Screenshot__

<img width="438" alt="screen shot 2016-05-07 at 20 34 10" src="https://cloud.githubusercontent.com/assets/922411/15093872/1fbb25f6-1494-11e6-9b02-1baf9318aef6.png">

**Comment by Ubonrat** [comment]
Fixed
