### ISSUE TITLE
Unimplemented feature "Favourite" on "hire" candidate page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#153]
__Description__

Unimplemented feature "Favourite" on "hire" candidate page

__Severity__: Unimplemented feature / Misleading UX

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidate/286

__Role__: Company user

__How to recreate it__

1. Login as company user
2. Click on a job with candidates
3. Click on "Chose candidate"
4. Click on a candidate

__Expected outcome__: No "Favourite" text or icon displayed.

__Screenshot__

<img width="365" alt="screen shot 2016-05-07 at 20 49 00" src="https://cloud.githubusercontent.com/assets/922411/15093904/28bf9a3c-1495-11e6-8cd5-acf18bdcf7a8.png">

**Comment by FivelFred** [comment]
This feature is not to be implemented for first release according to agreement with @chris-sedp when setting the scope.

**Comment by buren** [comment]
Closed by #187
