### ISSUE TITLE
Implement User competence-text field

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#154]
__Description__

Non-existing field "Competences" on "hire" candidate page

__Severity__: Misleading UX

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidate/286

__Role__: Company user

__How to recreate it__

1. Login as company user
2. Click on a job with candidates
3. Click on "Chose candidate"
4. Click on a candidate

__Expected outcome__: No field "competences" displayed.

__Screenshot__

<img width="365" alt="screen shot 2016-05-07 at 20 49 00" src="https://cloud.githubusercontent.com/assets/922411/15093904/28bf9a3c-1495-11e6-8cd5-acf18bdcf7a8.png">

**Comment by buren** [comment]
Closed by #188

**Comment by buren** [comment]
This is to be readded

**Comment by buren** [comment]
This field has now been implemented in the API, sorry for the confusion. The field is optional and works just like `education`. https://github.com/justarrived/just_match_api/pull/391

**Comment by ti-sedp** [comment]
fixed add competence text back
