### ISSUE TITLE
Unimplemented feature "Send message" on chose candidate page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#155]
__Description__

Unimplemented feature "Send message" on chose candidate page. When clicking "Send message" a hard coded chat is displayed and its not possible to send a message; no request is sent to the API and nothing happens visually. 

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidate/286

__Role__: Company user

__How to recreate it__

1. Login as company user
2. Click on a job that has candidates
3. Click on "Chose candidate"
4. Click on a candidate in the list
5. Click on "Send message"

__Expected outcome__: The real chat is displayed.

__Screenshot__

<img width="361" alt="screen shot 2016-05-07 at 21 08 11" src="https://cloud.githubusercontent.com/assets/922411/15094002/d693aad4-1497-11e6-94c2-bc20ccc4c4f4.png">

**Comment by FivelFred** [comment]
Should be possible to chat here.

**Comment by buren** [comment]
Should be closed by #210

**Comment by Ubonrat** [comment]
Fixed.
