### ISSUE TITLE
Unimplemented feature Translate from X in "Send message" view on chose candidate page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#156]
__Description__

Unimplemented feature Translate from X in "Send message" view on chose candidate page.
__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidate/286

__Role__: Company user

__How to recreate it__

1. Login as company user
2. Click on a job that has candidates
3. Click on "Chose candidate"
4. Click on a candidate in the list
5. Click on "Send message"
6. Click on "Translate from X"

__Expected outcome__: The chat is translated to the current users chosen locale.

__Screenshot__

<img width="361" alt="screen shot 2016-05-07 at 21 08 11" src="https://cloud.githubusercontent.com/assets/922411/15094002/d693aad4-1497-11e6-94c2-bc20ccc4c4f4.png">

**Comment by FivelFred** [comment]
![skarmavbild 2016-05-08 kl 10 50 32](https://cloud.githubusercontent.com/assets/16607246/15096885/b9cada4e-150a-11e6-93bc-f3a33d64b366.png)

**Comment by FivelFred** [comment]
The functionality above should be on every user generated text.
