### ISSUE TITLE
Unimplemented feature "References" on chose candidate page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#157]
__Description__

Unimplemented feature "References" on chose candidate page. When clicking "References" nothing is displayed and no request is made to the API

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidate/286

__Role__: Company user

__How to recreate it__

1. Login as company user
2. Click on a job that has candidates
3. Click on "Chose candidate"
4. Click on a candidate in the list
5. Click on "References"

__Expected outcome__: The users ratings and comments are displayed.

__Screenshot__

<img width="357" alt="screen shot 2016-05-07 at 21 12 53" src="https://cloud.githubusercontent.com/assets/922411/15094029/7eb7a3b4-1498-11e6-9ec6-5541db9e7ff0.png">

**Comment by ti-sedp** [comment]
Fixed
![2559-05-09_02h11_41](https://cloud.githubusercontent.com/assets/16758634/15100284/8933e0c8-1597-11e6-9ec1-c11aa38131a3.png)
