### ISSUE TITLE
Missing translations on "hire" candidate page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#158]
__Description__

Mixed content on page.

__Severity__: Wrong translations

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidate/286

__Role__: Company user

__How to recreate it__

1. Login as company user
2. Click on a job that has candidates
3. Click on "Chose candidate"
4. Click on a candidate in the list

__Expected outcome__: Content in the same language is displayed.

__Screenshot__

<img width="365" alt="screen shot 2016-05-07 at 20 49 00" src="https://cloud.githubusercontent.com/assets/922411/15094033/b0bdc618-1498-11e6-9840-74eed28eb683.png">

**Comment by Ubonrat** [comment]
Fixed.
