### ISSUE TITLE
Wrong acceptance time displayed on "hire" confirmation page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#159]
__Description__

The confirm page states that the user has 12 hours to accept the job, which is in correct, it should be 18 hours.

__Severity__: Wrong information

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidate/286

__Role__: Company user

__How to recreate it__

1. Login as company user
2. Click on a job that has candidates
3. Click on "Chose candidate"
4. Click on a candidate in the list
5. Click on "Hire"/"Anlita"

__Expected outcome__: The correct information is displayed.

__Screenshot__

<img width="330" alt="screen shot 2016-05-07 at 21 17 12" src="https://cloud.githubusercontent.com/assets/922411/15094045/23171ad4-1499-11e6-854b-19cf31f0e1ec.png">

**Comment by buren** [comment]
Its now possible to get the date time, directly from the API, when the candidate will have to confirm their participation (in other words set `will_perform`).

See https://github.com/justarrived/just_match_api/pull/380

**Comment by buren** [comment]
#159 related

**Comment by Ubonrat** [comment]
Fixed.
