### ISSUE TITLE
Missing translation on confirm "hire" page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#160]
__Description__

Missing translation on confirm "hire" page

__Severity__: Missing translation

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidate/286

__Role__: Company user

__How to recreate it__

1. Login as company user
2. Click on a job that has candidates
3. Click on "Chose candidate"
4. Click on a candidate in the list
5. Click on "Hire"/"Anlita"

__Expected outcome__: Translation is displayed.

__Screenshot__

<img width="330" alt="screen shot 2016-05-07 at 21 17 12" src="https://cloud.githubusercontent.com/assets/922411/15094045/23171ad4-1499-11e6-854b-19cf31f0e1ec.png">

**Comment by chris-sedp** [comment]
The translation keys are there and the translation also. Leaving this to you @FivelFred
