### ISSUE TITLE
Wrong time remaining displayed for an accepted user

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#161]
__Description__

Currently the remaining time is displayed for a user to accept a job calculated from 12 hours and not 18.

__Severity__: Wrong information

__URL__: http://justarrived.dev-machine.com/#/company/job/107/candidate/286

__Role__: Company user

__How to recreate it__

1. Login as a company user
2. Goto to a job with an accepted user

__Expected outcome__: The time remaining calculated from 18 hours, not 12. 

__Screenshot__

<img width="410" alt="screen shot 2016-05-07 at 21 22 02" src="https://cloud.githubusercontent.com/assets/922411/15094097/79ab817c-149a-11e6-8052-40e8016b9415.png">

**Comment by buren** [comment]
Its now possible to get the date time, directly from the API, when the candidate will have to confirm their participation (in other words set `will_perform`).

See https://github.com/justarrived/just_match_api/pull/380

**Comment by ti-sedp** [comment]
Check remain time between will-perform-confirmation-by and now instead

![2559-05-09_02h59_06](https://cloud.githubusercontent.com/assets/16758634/15100078/1a4a0b92-1592-11e6-8b60-d7c70e458b28.png)
