### ISSUE TITLE
No way to add payment details

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#162]
__Description__

The view where a user can add there payment details doesn't send any requests to the API. (FYI there is a field `frilans_finans_payment_details` returned for users that is true only if the user has already filled out those fields (so the user doesn't have to fill them in every time).

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/arriver/job/:id

__Role__: User

__How to recreate it__

1. Login in as regular user
2. Click on a job where the user is accepted for the job, but has not yet confirmed it
3. Accept the job
4. Fill out the payment details
5. Click continue

__Expected outcome__: Payment details sent to the API

__Screenshot__

<img width="437" alt="screen shot 2016-05-07 at 21 47 38" src="https://cloud.githubusercontent.com/assets/922411/15094202/60ae249c-149d-11e6-8ad3-34bccd27d27f.png">

**Comment by buren** [comment]
One more thing where it says "Bank" it should really be the "Account clearing number" and "Kortnummer" , should really be "Account number"

**Comment by ti-sedp** [comment]
Should we hide  IBAN - nummer field and BIC - nummer field ?

**Comment by buren** [comment]
I just added support for those 2 in the API https://github.com/justarrived/just_match_api/pull/381. 

The PR will be merged & deployed within a few minutes.

**Comment by FivelFred** [comment]
BIC and IBAN should be expandable. They are not standard but should be an option.

**Comment by buren** [comment]
fyi: The API will look for `account-clearing-number` & `account-number` first and if no such values are found in the request body it will _then_ look for `iban` & `bic`.
