### ISSUE TITLE
Misleading button title for hired user on job show page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#163]
__Description__

Currently the button that allows a hired user to indicate that they've performed only says "Ja", making it impossible to know what the button does.

__Severity__: Wrong/misleading copy

__URL__: http://justarrived.dev-machine.com/#/arriver/job/107

__Role__: Hired user

__How to recreate it__

1. Login as a regular user
2. Goto a job where the user has been hired and the job date is in the past

__Expected outcome__: The button says something a long the lines of "Confirm performance of job"

__Screenshot__

<img width="439" alt="screen shot 2016-05-07 at 21 54 43" src="https://cloud.githubusercontent.com/assets/922411/15094259/b92edf98-149e-11e6-93db-e288f1d6693c.png">

**Comment by FivelFred** [comment]
It should be one Button that says "Ge besked" in Swedish. Me and @chris-sedp decided to ditch the "Skicka meddellanden" as the chat is available below

**Comment by buren** [comment]
@FivelFred the problem here is actually not the "Send message" button but the button that says "Ja", which actually makes the user confirm that they've performed the job...

**Comment by chris-sedp** [comment]
This one is solved. Closing
