### ISSUE TITLE
Broken link "Archive"/"Arkiv" for user

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#164]
__Description__

The link "Archive"/"Arkiv" on "My assignments" page doesn't do anything.

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/arriver/jobs

__Role__: User

__How to recreate it__

1. Login as a regular user
2. Goto "My assignments" page

__Expected outcome__:  A list of all previous jobs where invoices have been created.

__Screenshot__

<img width="443" alt="screen shot 2016-05-07 at 22 04 40" src="https://cloud.githubusercontent.com/assets/922411/15094325/2821cbda-14a0-11e6-8071-8f6644571b7b.png">

**Comment by ti-sedp** [comment]
Fixed
![2559-05-11_12h03_53](https://cloud.githubusercontent.com/assets/16758634/15170492/7e29d11c-1770-11e6-88fb-571a7bf94a7d.png)
