### ISSUE TITLE
"My assignments" page for company user broken

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#165]
__Description__

There is an exception thrown on the page "My assignments" for a logged in company users. I'm not sure how/if it brakes other features on that page. The culprit seems to be that the code assumes that there always are a user image, which is *not* the case.

The line that causes the exception is [CompanyJobCtrl.js:59](https://github.com/justarrived/just-match-frontend/blob/master/src/app/common/controllers/CompanyJobCtrl.js#L59).

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/company/jobs

__Role__: Company user

__How to recreate it__

1. Login in as a company user
2. Goto a job where a user has applied that has no profile image

__Screenshot__

<img width="1126" alt="screen shot 2016-05-07 at 22 13 42" src="https://cloud.githubusercontent.com/assets/922411/15094372/b0c20efe-14a1-11e6-9af5-6c3d6c22870e.png">

**Comment by ti-sedp** [comment]
Fixed
