### ISSUE TITLE
Company user can't create invoice

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#166]
__Description__

Currently there seems to be now way for a company user to create an invoice / confirm the users performance. 

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/company/jobs

__Role__: Company user

__How to recreate it__

1. Login as a company
2. Make sure there is a user that has been hired and the job date is in the passed
2. Goto "My assignments"

__Expected outcome__: The job is listed and it should be possible to create an invoice.

__Screenshot__

<img width="367" alt="screen shot 2016-05-07 at 22 26 07" src="https://cloud.githubusercontent.com/assets/922411/15094395/bbac06a2-14a2-11e6-8e03-769627257c66.png">

**Comment by ti-sedp** [comment]
Can you send me username and password that you use?

**Comment by buren** [comment]
@ti-sedp

email: wirattic@seproduction.com
password: 12345678
job id: 107

**Comment by ti-sedp** [comment]
Fixed (Uploading to dev-manchine server)

For some reason angular $filter cannot filter correctly when try to filter object is not null.
try to set filter option like this
```
relationships: {
    invoice: {
        data: '!NULL'
    }
}
```
