### ISSUE TITLE
Broken back button on /warning page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#168]
__Description__

The back button doesn't work on the "warning" page.

__Severity__: Can't continue

__URL__: http://justarrived.dev-machine.com/#/warning

__Role__: User

__How to recreate it__

1. Login as regular user
2. Goto start page
3. Click on "Post your mission here!"/"Lägg upp ditt uppdrag här!"

__Expected outcome__: Redirect back to start page

**Comment by ti-sedp** [comment]
Fixed
Use flow.completed instead

**Comment by ti-sedp** [comment]
Fixed
