### ISSUE TITLE
Missing translation/content on /warning page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#169]
__Description__

There is missing translations on the /warning page.

__Severity__: Wrong content/translation

__URL__: http://justarrived.dev-machine.com/#/warning

__Role__: User

__How to recreate it__

Login as regular user
Goto start page
Click on "Post your mission here!"/"Lägg upp ditt uppdrag här!"

__Expected outcome__: Translated content

__Screenshot__

<img width="540" alt="screen shot 2016-05-07 at 23 13 39" src="https://cloud.githubusercontent.com/assets/922411/15094603/b8055e98-14a9-11e6-9864-59c0dda1517d.png">

**Comment by chris-sedp** [comment]
This one is fixed and on the dev-machine
