### ISSUE TITLE
Broken create company flow when there is an API validation error

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#170]
__Description__

When creating a company where the API returns a validation error it gets fairly hard for a user to complete the registration. Users will get stuck or be forced to "start over". 

__Severity__: Difficult to complete action

__URL__: http://justarrived.dev-machine.com/#/company/register

__Role__: Not logged in

__How to recreate it__

1. Make sure you're logged out
2. Goto start page
3. Click on "Post your mission here!"
4. Click on "login.select.register-email" (btw broken translation..)
5. Click on "Select.."
6. Fill in a non-existing "Swedish organisation number" (or cin as its known in the API)
7. Click on "Create new cin" (Should really say "Create new company")
8. Fill in valid details, except for the company website, then fill in a website without the protocol (http/https)
9. Submit the form

The page is reloaded and all fields are "grayed out", in order to continue the user has to realise that step 1 to 7 (detailed above) needs to be re-done in order to fix the validation error (which is not displayed in the UI).

__Expected outcome__: A validation error stating that http or https is required and the company fields to be enabled.

__Screenshot__

<img width="425" alt="screen shot 2016-05-07 at 23 24 20" src="https://cloud.githubusercontent.com/assets/922411/15094687/e0bbd5ee-14ac-11e6-9ce1-7e3604884d43.png">

**Comment by ti-sedp** [comment]
Fixed
support error message from api can continue register company
