### ISSUE TITLE
Broken back button on select-company page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#171]
__Description__

Broken back button on select-company page

__Severity__: Can't go back

__URL__: http://justarrived.dev-machine.com/#/user/select-company

__Role__: Not logged in

__How to recreate it__

1. Make sure you're logged out
2. Goto to the start page
3. Click on "Post your mission here!"

On the next page there is now way to go back.

__Expected outcome__: Redirect back to previous page

__Screenshot__

<img width="392" alt="screen shot 2016-05-07 at 23 42 23" src="https://cloud.githubusercontent.com/assets/922411/15094703/5f74a910-14ad-11e6-845a-eda757d38fc8.png">

**Comment by ti-sedp** [comment]
Fixed
