### ISSUE TITLE
API validations not displayed on register company page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#172]
__Description__

If the API returns validation errors they aren't displayed in the UI. Related to #170 

__Severity__: Can't complete action (or at least there is not way for the user to find out whats wrong)

__URL__: http://justarrived.dev-machine.com/#/company/register

__Error message__: None

__Role__: Not logged in

__How to recreate it__

1. Make sure you're logged out
2. Goto start page
3. Click on "Post your mission here!"
4. Click on "login.select.register-email" (btw broken translation..)
5. Fill out valid details but don't include the protocol (https/http) for the website

__What happens__

Page is reloaded, no validation errors on page

__Expected outcome__: Validation error from API displayed.

__Screenshot__

<img width="425" alt="screen shot 2016-05-07 at 23 24 20" src="https://cloud.githubusercontent.com/assets/922411/15094727/3151e560-14ae-11e6-916d-a12de705eb91.png">

**Comment by buren** [comment]
Same problem for all API validations...

**Comment by ti-sedp** [comment]
Fixed
api error show in company register form

**Comment by chris-sedp** [comment]
verified this one and closing
