### ISSUE TITLE
Neither company images or user images are uploaded before submit

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#173]
__Description__

The image uploading is designed to enable the UI seem fast and fluid from a users point of view. Therefore images are supposed to be uploaded to the backend as soon as a user choses an image. Instead of waiting for the user to submit the form, waiting for the image to upload, grabbing the image one time token and then submitting the "main" form. This causes a quite long wait for the user.

Instead upload the image instantly.

__Severity__: Bad performance/UX

__URL__: Register company & user page

__Expected outcome__: The image has already been uploaded when user submits the form.

**Comment by ti-sedp** [comment]
Fixed upload image after browse image file in settings page, company register, user profile
