### ISSUE TITLE
Missing 404 page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#175]
__Description__

Even though no route exists 200 is always returned (with no content). Instead return a 404 status with a message "Page not found" or something like that.

__URL__: Any missing URL

__How to recreate it__

1. Goto a missing page

__What happend__

A blank page is returned with 200 ok status.

__Expected outcome__

404 status with a message stating "Page not found".

__Screenshot__

<img width="446" alt="screen shot 2016-05-08 at 11 36 14" src="https://cloud.githubusercontent.com/assets/922411/15097089/635423da-1511-11e6-85ea-be128fd6c4c4.png">

**Comment by ti-sedp** [comment]
Fixed wait for content and design

![2559-05-11_18h21_33](https://cloud.githubusercontent.com/assets/16758634/15179385/7a1a6b9c-17a5-11e6-9bc8-2bf788c53b62.png)

**Comment by Ubonrat** [comment]
Fixed.
