### ISSUE TITLE
Allow a company user to create an invoice before JobUser#performed

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#176]
__Description__

Currently the company user can't create an invoice until the JobUser has set performed=true, this is not necessary. The company user should be able to create an invoice as long as the will_perform is true and the job has been "started" (job date in the passed).

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/company/job/105/candidate/288

__Role__: Company user

__How to recreate it__

1. Login as company user
2. Chose a job where there is a "hired" candidate and where the job date is in the passed

__What happend__

Not possible to create an invoice.

__Expected outcome__

Allow the company user to create an invoice.

__Screenshot__

Expected view:

<img width="383" alt="screen shot 2016-05-08 at 12 17 49" src="https://cloud.githubusercontent.com/assets/922411/15097279/e55a3ce8-1516-11e6-8e53-31ce405e144e.png">

---
---

Actual view:

<img width="381" alt="screen shot 2016-05-08 at 12 18 12" src="https://cloud.githubusercontent.com/assets/922411/15097288/fb467968-1516-11e6-93da-97d23e12ddc1.png">

**Comment by ti-sedp** [comment]
Fixed Company can create invoice at **will-perform:true**
I try to user Company user set **performed:true** but api don't set **performed:true**
however it can create invoice in **will-perform:true** and **performed:false**

**Comment by buren** [comment]
> I try to user Company user set performed:true but api don't set performed:true

Thats not for the Company user to set, that value can only be set by the Job user.

> however it can create invoice in will-perform:true and performed:false

Thats by design, the Company user should be able to create an invoice even though the Job user hasn't yet confirmed that they've performed the job.
