### ISSUE TITLE
Can not go back in Create Profile

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#179]
__Description__

As a job performer you can not go back to alter your profile once you reached the step where you fill in free text about yourself. 

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/user

__Role__: user 

__How to recreate it__

1. Go to start page
2. Click "Sign up here" link
3. Enter details in first step
4. In the next step try to click on arrow back (top left)

__What happend__

Nothing

__Expected outcome__

To come back to the previous view. 

__System__: OSX

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome 50

__Screenshot__

![skarmavbild 2016-05-08 kl 13 52 42](https://cloud.githubusercontent.com/assets/16607246/15097716/fa15f8f8-1524-11e6-96b1-ca1124da7ad9.png)

**Comment by ti-sedp** [comment]
Fixed cannot go back after success register new arriver user step1
