### ISSUE TITLE
Missing translation for "Post your mission here" view - LOGIN.SELECT.TITLE

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#180]
__Description__

Missing translation

__Severity__: Copy

__URL__: http://justarrived.dev-machine.com/#/user/select-company

__Role__: Not logged in

__How to recreate it__

1. Start page
2. Click "Post your mission here"

__What happend__

Get alternative to create account or log-in. Text keys are displayed instead of actual translations. 

__Expected outcome__

To go straight to log-in and have the option to create an account (by link). With correctly fetched text strings. 

__System__: OSX

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome 50
![skarmavbild 2016-05-08 kl 14 15 44](https://cloud.githubusercontent.com/assets/16607246/15097787/75a23862-1528-11e6-9203-d3e42c1bbcd1.png)

__Screenshot__

Take a screenshot of the error.

**Comment by chris-sedp** [comment]
Fixed new copy for translation
Fixed correct registration routes
Will be deployed together with the other translation issues
