### ISSUE TITLE
Can not reset password

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#182]
__Description__

Link for "Forgotten password" is not clickable. Nothing happens. Also get the text in Swedish and not english as it should be. 

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/user/signin

__Role__: Not logged in

__How to recreate it__

1. Goto starting page
2. Click meny
3. Click sign-in
4. Click "Glömt lösenord?"

__What happend__

Nothing

__Expected outcome__

To get a notification that a new password has been sent. 

No error message.

__System__: OSX

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome 50
![skarmavbild 2016-05-08 kl 14 26 18](https://cloud.githubusercontent.com/assets/16607246/15097821/726dbada-1529-11e6-9e61-0b47eeb62538.png)

__Screenshot__

Take a screenshot of the error.

**Comment by FivelFred** [comment]
Please provide URL for reset to Jacob Burenstam

**Comment by buren** [comment]
I'll need the URL that I should put in the reset password email, so that you then can pick on the `reset-token`.

**Comment by ti-sedp** [comment]
What api url i have to call for this feature?
How about "user/reset/:reset_token" ?

**Comment by buren** [comment]
http://localhost:3000/api_docs/1.0/reset_password/create.html

**Comment by ti-sedp** [comment]
Fixed
