### ISSUE TITLE
Contact form verification is not in choose language and capital letters on every single word

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#183]
__Description__

When sending a contact request / question the copy is wrong and not in english. 

__Severity__: Wrong translation

__URL__: http://justarrived.dev-machine.com/#/user

__Role__: user 

__How to recreate it__

1. Go to menu
2. Click contact
3. Fill in form
4. Press send

__What happend__

Text is displayed with capital letters on every word. Button that says "Tillbaka" (back) is Swedish although language is set to english.

__Expected outcome__

English text and not capital letters. 
![skarmavbild 2016-05-08 kl 14 56 00](https://cloud.githubusercontent.com/assets/16607246/15097918/01805068-152d-11e6-832c-a8c1fafe66da.png)

__Screenshot__

Take a screenshot of the error.

**Comment by Ubonrat** [comment]
Fixed.
