### ISSUE TITLE
Can't change primary language on settings page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#189]
__Description__

Can't change primary language settings page.

__Severity__: Can't complete action

__Role__: User

__How to recreate it__

1. Login as user
2. Open menu
3. Click the "gear"-icon button right corner
4. Click on language field

__What happend__: Nothing

__Expected outcome__: Be able to chose a new primary language (system language)

__Screenshot__

<img width="401" alt="screen shot 2016-05-08 at 15 38 45" src="https://cloud.githubusercontent.com/assets/922411/15098090/30aaab94-1533-11e6-9563-a391db2ab621.png">

**Comment by buren** [comment]
Relevant code https://github.com/justarrived/just-match-frontend/blob/e96c37606d2525eae8292158df33bd686d4d7ce2/src/app/common/templates/settings.html#L46

**Comment by ti-sedp** [comment]
Fixed
