### ISSUE TITLE
Wrong field name for user Social Security Number

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#190]
__Description__

On the users settings page it says "Organisation number" and not "Social Security Number".

Hard coded in: https://github.com/justarrived/just-match-frontend/blob/e96c37606d2525eae8292158df33bd686d4d7ce2/src/app/common/templates/settings.html#L20

__Role__: User

__How to recreate it__

1. Login as user
2. Open menu
3. Click the "gear"-icon button right corner

__Screenshot__

<img width="401" alt="screen shot 2016-05-08 at 15 38 45" src="https://cloud.githubusercontent.com/assets/922411/15098108/e06886dc-1533-11e6-8996-20e739def5a7.png">

**Comment by ti-sedp** [comment]
Company User Setting field Fixed
![2559-05-17_11h07_24](https://cloud.githubusercontent.com/assets/16758634/15310940/8f45972a-1c1f-11e6-8e98-a4759166166c.png)
