### ISSUE TITLE
Broken styling on settings page if there is an open dropdown

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#191]
__Description__

Language dropdown visible on top of user settings page.

__Severity__: Broken styling

__URL__: http://justarrived.dev-machine.com/#/user

__Role__: User

__How to recreate it__

1. Login as user
2. Goto user profile page
3. Open the "language skill" dropdown
  - Don't close the language dropdown
4. Open the menu
5. Click the "gear"-icon 

__What happend__

The language dropdown is displayed on top of the settings page.

__Browser__: Chrome (OSX)

__Screenshot__

<img width="406" alt="screen shot 2016-05-08 at 15 46 32" src="https://cloud.githubusercontent.com/assets/922411/15098135/8bda410e-1534-11e6-9be4-033e41bd2bd2.png">

**Comment by Ubonrat** [comment]
Fixed.
