### ISSUE TITLE
Can't upload user image on profile page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#193]
__Description__

The UI shows the profile image circle at the top with the text "Add image" on top and I get the "chose file popup", no image is uploaded.

__Severity__: Can't complete action

__URL__: http://justarrived.dev-machine.com/#/user

__Error message__: None

__Role__: User

__How to recreate it__

1. Make sure you're not logged in
2. Create user
3. On the user profile page click "Add image"
4. Chose an image

__What happend__: Nothing

__Expected outcome__: An image is uploaded

__Browser__: Chrome (OSX)

__Screenshot__

<img width="557" alt="screen shot 2016-05-08 at 17 12 01" src="https://cloud.githubusercontent.com/assets/922411/15098581/a628c5d8-1540-11e6-9636-738f1eaf7a0d.png">

**Comment by ti-sedp** [comment]
Fixed
