### ISSUE TITLE
Add Google Analytics 

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#202]
We need to add Google Analytics in order to be able to track user behaviour on the site.

@FivelFred can you create a Google Analytics account at www.google.com/analytics/ and then give the JavaScript snippet to add to each page. If you want help/guidance just let me know.

**Comment by chris-sedp** [comment]
@FivelFred Do we have the GA key ?

**Comment by FivelFred** [comment]
I will fix when I get to work


Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Christopher <notifications@github.com> 
Datum: 05-17-2016  04:48  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Add Google Analytics  (#202) 

@FivelFred Do we have the GA key ?

**Comment by FivelFred** [comment]
Is this done @chris-sedp ?

**Comment by FivelFred** [comment]
I tried to send "test-traffic" and it wasn´t working. Could you update the tracking code @chris-sedp ?

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77971132-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by FivelFred** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77971132-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by FivelFred** [comment]
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77971132-1', 'auto');
  ga('send', 'pageview');

**Comment by buren** [comment]
We should make sure that the setup works for Angular.

https://github.com/revolunet/angular-google-analytics seems promising.

**Comment by FivelFred** [comment]
What will this enable? Is it critical? @buren

**Comment by FivelFred** [comment]
Ok, can you implement this @ti-sedp ?

**Comment by ti-sedp** [comment]
OK
