### ISSUE TITLE
Previous page arrow doesn't respond

### ISSUE THREAD

**Issue by justarrived-bugbash-1** [justarrived/just-match-frontend#247]
__Description__

The previous page icon "<" doesn't work.

__Severity__:

_Chose one of the below:_

* Can perform with problem

__URL__: http://justarrived.dev-machine.com/#/user/select-company

__Error message__: The error message displayed, if any.
<img width="1274" alt="screen shot 2016-05-09 at 18 15 13" src="https://cloud.githubusercontent.com/assets/19267466/15119617/0544b0dc-1612-11e6-9cd1-f1eb60440449.png">

__Role__: Not logged in

__How to recreate it__

1. Go to http://justarrived.dev-machine.com/#/
2. Click "Upload your job here"

__What happend__

__Expected outcome__

The arrow would take me to the previous page.

No error message.

__System__: OSX and iOS

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

Take a screenshot of the error.

**Comment by FivelFred** [comment]
See #171

**Comment by ti-sedp** [comment]
Fixed
