### ISSUE TITLE
No content displayed when pressing "submit for review"

### ISSUE THREAD

**Issue by justarrived-bugbash-1** [justarrived/just-match-frontend#248]
__Description__

When pressing "Submit for review" no content is displayed.

__Severity__:

_Chose one of the below:_

* Can not perform action

__URL__: http://justarrived.dev-machine.com/#

__Error message__: The error message displayed, if any.
<img width="1278" alt="screen shot 2016-05-09 at 18 25 44" src="https://cloud.githubusercontent.com/assets/19267466/15119921/788c77b8-1613-11e6-8aaa-eaeb6e022f77.png">

__Role__: Not logged in

__How to recreate it__

1. Go to the start page
2. Click a job
3. Click "Submit for review"

__What happend__

Just the header and the footer are displayed, no content in the middle. 

__Expected outcome__

Something would be displayed guiding me on how to "submit something for review".
<img width="1278" alt="screen shot 2016-05-09 at 18 25 44" src="https://cloud.githubusercontent.com/assets/19267466/15120023/e6d673d6-1613-11e6-825e-95f4ffb6e927.png">

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

Take a screenshot of the error.

**Comment by chris-sedp** [comment]
@fivelFred we remove the link and close this one as we don't have any mockup for it or any logic behind this functionality.
