### ISSUE TITLE
Wrong anchor point for "show more jobs"

### ISSUE THREAD

**Issue by justarrived-bugbash-1** [justarrived/just-match-frontend#249]
__Description__

When clicking any arrow at the bottom of the job list I end up too high up on the page and the user experience feels a bit messy.

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/jobs/106

__Error message__: The error message displayed, if any.

__Role__: Not logged in

__How to recreate it__

1. Goto http://justarrived.dev-machine.com/#/jobs/106
2. Click one of the arrows "<< < > >>" at the bottom of the jobs list. 

__What happend__

When the new page loaded to display more jobs, the anchor point took me to almost the top of the page instead of the top of the job list, making the user experience a bit messy for me.

__Expected outcome__

To land at top of jobs list, possibly even without a single job to still be displayed at the top. Alternatively that a new "job list view" is loaded without the whole page reloading.

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome Version 50.0.2661.86 (64-bit)

__Screenshot__
<img width="1276" alt="screen shot 2016-05-09 at 18 36 43" src="https://cloud.githubusercontent.com/assets/19267466/15120232/0351ab7e-1615-11e6-90ba-d848938ea545.png">

Take a screenshot of the error.

**Comment by ti-sedp** [comment]
Fixed after change page the scrollbar will auto scroll to the top of job list
both job list and job detail page
