### ISSUE TITLE
Translation error in my jobs

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#250]
Team 4

__Description__

The translation of the page is not correct.

__Severity__:

_Chose one of the below:_

* Translation error

__URL__:  http://justarrived.dev-machine.com/#/company/jobs

__Error message__: 

__Role__: Company user

__How to recreate it__

1. Visit my jobs

__What happend__

Translation was not correct.

__Expected outcome__

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

Take a screenshot of the error.
![screenshot 2016-05-09 18 32 52](https://cloud.githubusercontent.com/assets/3882707/15120259/23ac19fe-1615-11e6-8cb2-2f8888dd7d94.png)

**Comment by chris-sedp** [comment]
@FivelFred The keys are there but they need to translated. I will remove the bug label on this one and only keep the translations label. All issues with only translations label i will leave to you.

**Comment by FivelFred** [comment]
Ok sounds good!


Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Christopher <notifications@github.com> 
Datum: 05-17-2016  06:45  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Translation error in my jobs
  (#250) 

@FivelFred The keys are there but they need to translated. I will remove the bug label on this one and only keep the translations label. All issues with only translations label i will leave to you.
