### ISSUE TITLE
Comments is not showing my name and my picture (shows someone else's picture)

### ISSUE THREAD

**Issue by yatinnova** [justarrived/just-match-frontend#252]
__Description__

Comments is not showing my picture

__Severity__:

_Chose one of the below:_
* Can perform with problem

__URL__: http://justarrived.dev-machine.com/#/jobs/113

__Error message__: The error message displayed, if any. NA

__Role__: User

__How to recreate it__

1. Type a chat message on a job

__What happend__

__Expected outcome__

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome
__Screenshot__
![1](https://cloud.githubusercontent.com/assets/17121324/15120379/bf6c7b72-1615-11e6-91f1-74f0a7c597b2.png)

Take a screenshot of the error.

**Comment by ti-sedp** [comment]
https://just-match-api-staging.herokuapp.com/api_docs/1.0/comments/index.html
Can you add owner.user-images to this one?

**Comment by buren** [comment]
Deployed a fix for this, you can now inline user images `/api/v1/jobs/1/comments/?include=owner.user-images`. The docs have also been updated.
