### ISSUE TITLE
Button loading in wrong language

### ISSUE THREAD

**Issue by justarrived-bugbash-1** [justarrived/just-match-frontend#253]
__Description__

After filling out the "Contact us" form, the pink "Back" button on the sent message confirmation screen displays in Swedish instead of English.

__Severity__:

_Chose one of the below:_

* Translation error

__URL__: http://justarrived.dev-machine.com/#/contact/completed

__Error message__: The error message displayed, if any.

__Role__: Not logged in

__How to recreate it__

1. Goto "Contact us" under the menu
2. Fill out the form and click "send"

__What happend__

A button with "Tillbaka" is displayed at the end of the message.

__Expected outcome__

That the button would display "Go back".

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome 
<img width="1277" alt="screen shot 2016-05-09 at 18 39 39" src="https://cloud.githubusercontent.com/assets/19267466/15120439/ffe89a28-1615-11e6-8d6c-33ce502f1192.png">

__Screenshot__

Take a screenshot of the error.

**Comment by chris-sedp** [comment]
fixed
