### ISSUE TITLE
Missing company logos

### ISSUE THREAD

**Issue by justarrived-bugbash-1** [justarrived/just-match-frontend#256]
On the bottom of the start page there is a bunch of company logos.

The Nova logo and "Jacob Burenstam" logo should be there too. @FivelFred will provide them.

**Comment by buren** [comment]
Neither is "Jacob Burenstam"!

**Comment by buren** [comment]
@FivelFred can you provide logos for this 👼

**Comment by FivelFred** [comment]
Yes, I will upload them here later.

**Comment by FivelFred** [comment]
Elena will take care of this one

**Comment by Ekman1991** [comment]
We assume that Elena will take care of this one. Otherwise where do we find the logos?

**Comment by FivelFred** [comment]
I will try to upload them tonight. The ones I have.


Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Philip Ekman <notifications@github.com> 
Datum: 05-16-2016  17:56  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Missing company logos (#256) 

We assume that Elena will take care of this one. Otherwise where do we find the logos?

**Comment by FivelFred** [comment]
![janssonnorin-710x270](https://cloud.githubusercontent.com/assets/16607246/15296817/6a3a828e-1b97-11e6-8a7d-ff24507b1a68.png)
![antrop-logo-black](https://cloud.githubusercontent.com/assets/16607246/15296819/6c0332f0-1b97-11e6-8014-78601f1c183a.png)
![273e302](https://cloud.githubusercontent.com/assets/16607246/15296825/6eef660a-1b97-11e6-9a33-312a61bedd8e.png)
![cygni](https://cloud.githubusercontent.com/assets/16607246/15296826/70db1194-1b97-11e6-9b4d-833b20954625.jpg)

**Comment by FivelFred** [comment]
I started collecting logos but I think it is better if I email everyone involved and ask them to send the right ones as png. Hopefully Elena can help out.

**Comment by buren** [comment]
@FivelFred what about me? :)

**Comment by FivelFred** [comment]
Jacob Burenstam name should also be there! Of course 


Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Jacob Burenstam <notifications@github.com> 
Datum: 05-16-2016  18:55  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Missing company logos (#256) 

@FivelFred what about me? :)

**Comment by Ekman1991** [comment]
Can someone provide the "Jacob Burnestam" logo aswell as the Nova logo? Then I´ll add those and the logos you just sent @FivelFred

**Comment by FivelFred** [comment]
![logo-300x121](https://cloud.githubusercontent.com/assets/16607246/15301371/adae2e2e-1bad-11e6-9cdf-e6d4ca1f69de.png)

**Comment by FivelFred** [comment]
Jacob Burenstam does not have a logo, right @buren ?

**Comment by buren** [comment]
@FivelFred thats right... 

We could go with: 
<img width="145" alt="screen shot 2016-05-16 at 21 36 42" src="https://cloud.githubusercontent.com/assets/922411/15301526/5ee48f8a-1bae-11e6-9945-3d556c1aa529.png">

**Comment by FivelFred** [comment]
![bond_logo_shaded_full text_big](https://cloud.githubusercontent.com/assets/16607246/15354678/09b00f7a-1cef-11e6-8ef1-7c10f2ba9ee6.png)

**Comment by FivelFred** [comment]
So this is the complete list;

Partners and champions are the following;

Frilans Finans, Nova, Universum, Antrop, Cygni, Jansson&Norin, Bond Street, Jacob Burenstam, Yuliya Bilinskaya, Caroline He, Mattias Bengtsson

Enablers are the following;

Wintrgarden, Semantix, Stockholm Skrivarbyrå, Skeppsbron Skatt, Welcome!, Hero Sverige, Migrationsverket, Röda Korset, Never Ending Monday, Caroline Olsson,

**Comment by FivelFred** [comment]
![welcome](https://cloud.githubusercontent.com/assets/16607246/15420769/cc3f8220-1e6e-11e6-8006-6da39bcb6aac.PNG)

![sthlm skriv](https://cloud.githubusercontent.com/assets/16607246/15420837/32e4740e-1e6f-11e6-8eb5-a970eaa42dd6.jpg)

![semantix_toplogo](https://cloud.githubusercontent.com/assets/16607246/15420808/fc1eee40-1e6e-11e6-90de-37bf8e7a2e9b.png)

![skeppsbron_logo_brun_pms-410_-250x326](https://cloud.githubusercontent.com/assets/16607246/15420866/562a0ec4-1e6f-11e6-99a8-a9b1a29a7113.png)

![hero_logoer_rgb_svensk](https://cloud.githubusercontent.com/assets/16607246/15420889/75a01a6e-1e6f-11e6-92a1-a792e6418bcd.jpg)

![migrationsverket-680](https://cloud.githubusercontent.com/assets/16607246/15420911/90f40410-1e6f-11e6-9c24-16a0fcbdb71a.jpg)

![logo_rodakorset](https://cloud.githubusercontent.com/assets/16607246/15420924/a9ab7d26-1e6f-11e6-982c-56268194949b.png)

**Comment by lenaar** [comment]
I have added logo, it would be nice if someone can look and see if it looks good

**Comment by FivelFred** [comment]
Thank you Elena! I will have a look tomorrow. Maybe @chris-sedp and team can have a look?
Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: lenaar <notifications@github.com> 
Datum: 05-20-2016  20:54  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Missing company logos (#256) 

I have added logo, it would be nice if someone can look and see if it looks good
