### ISSUE TITLE
Can't find Dari, Tigrinja, Persiska, Somaliska, Pashto or Kurdiska

### ISSUE THREAD

**Issue by farshid12** [justarrived/just-match-frontend#257]
__Description__

Can't find Dari, Tigrinja, Persiska/Persian, Somaliska/Somali, Pashto or Kurdiska/Kurdish in the Swedish and English versions of the site.

__Severity__:

_Chose one of the below:_

* Can not perform action

__URL__: The URL that the error occurred on.

__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in

user

__How to recreate it__

1. Goto  create profile
2. Click "språkkunskaper"
3.

__What happend__

Searched for the mentioned languges and did'nt find any tags for them

__Expected outcome__

Expected to be able to choose these languges

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome/Firefox/Internet Firefox

__Screenshot__

Take a screenshot of the error.

**Comment by chris-sedp** [comment]
I found all of them except Persian. @buren do we have the persian language in the db ?

**Comment by FivelFred** [comment]
Persian has the language code fa

**Comment by chris-sedp** [comment]
@FivelFred aha.. the it should definitely be in there as its one of the system languages?

**Comment by chris-sedp** [comment]
@FivelFred ok... Its called Farsi in the db ... Problem solved. Im closing this one.

**Comment by FivelFred** [comment]
Yep. 


Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Christopher <notifications@github.com> 
Datum: 05-17-2016  09:09  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Can't find Dari, Tigrinja,
  Persiska, Somaliska, Pashto or Kurdiska (#257) 

@FivelFred aha.. the it should definitely be in there as its one of the system languages?
