### ISSUE TITLE
Unclear positioning of header

### ISSUE THREAD

**Issue by justarrived-bugbash-1** [justarrived/just-match-frontend#258]
__Description__

A design issue. Header is below the text that one expects it will follow.

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: The URL that the error occurred on.

__Error message__: The error message displayed, if any.

__Role__: Not logged in

__How to recreate it__

1. Goto http://justarrived.dev-machine.com/#/

__What happend__

The headers "This is how it works for emoloyees" and "Create your profile" are displayed beneath the pink and grey boxes instead of above. Feels unintuitive.

__Expected outcome__

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome
<img width="1276" alt="screen shot 2016-05-09 at 18 47 31" src="https://cloud.githubusercontent.com/assets/19267466/15120632/e59d6a30-1616-11e6-8f3f-ec6d33ac169e.png">

__Screenshot__

Take a screenshot of the error.

**Comment by FivelFred** [comment]
Header should be above details about how it works
