### ISSUE TITLE
When I try to edit profile settings, it's not obvious whether its saved or not

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#259]
Team 4

__Description__

Having save button at the bottom is not giving the feeling of saving. There is a close button on the corner and it's confusing to have both.

__Severity__:

_Chose one of the below:_

* New feature / suggestion

__URL__:  http://justarrived.dev-machine.com/#/

__Error message__: 

__Role__: user

__How to recreate it__

1. Go to settings
2. Click save
3. Nothing happens

__What happend__

Having save button at the bottom is not giving the feeling of saving. There is a close button on the corner and it's confusing to have both.

__Expected outcome__

An indication of saving and closing the window. After that, I expect it to go back or menu.

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

Take a screenshot of the error.

**Comment by ti-sedp** [comment]
Fixed goto setting after click save button show confirmation page and back to main menu after click back button

**Comment by FivelFred** [comment]
For me this is not possible. Only once but after that I can not update it again. If I refresh the page I get the message that it has been updated. Otherwise nothing happens (but I noticed that it is acctually saved). Please look into this @ti-sedp

**Comment by ti-sedp** [comment]
Fixed
