### ISSUE TITLE
Notification of new chat message is hard to see

### ISSUE THREAD

**Issue by andreaskoenig** [justarrived/just-match-frontend#261]
__Description__

Short description of the problem

__Severity__:

_Chose one of the below:_

* New feature / suggestion

__URL__: http://justarrived.dev-machine.com/#/arriver/job/115

__Error message__: The error message displayed, if any.

__Role__:  User 

__How to recreate it__

1. Goto ...
2. Click ...
3.

__What happend__
I did not receive any notification of receiving new messages

__Expected outcome__

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome/Firefox/Internet explorer version X

__Screenshot__

Take a screenshot of the error.
<img width="1280" alt="skarmavbild 2016-05-09 kl 18 49 52" src="https://cloud.githubusercontent.com/assets/19269861/15120733/63e0e17e-1617-11e6-83cf-a826b0d7bddb.png">

**Comment by FivelFred** [comment]
Should be possible to get notifications by e-mail in the first launch?

**Comment by FivelFred** [comment]
Can we close this @buren

**Comment by buren** [comment]
Closing this in favour of https://github.com/justarrived/just_match_api/issues/431
