### ISSUE TITLE
After existing from settings, redirected back to create profile page where continue button is not working.

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#262]
Team 4

__Description__

After existing from settings, redirected back to create profile page where continue button is not working.

__Severity__:

_Chose one of the below:_

* Can not perform action

__URL__: http://justarrived.dev-machine.com/#/user

__Error message__: 

__Role__: user

__How to recreate it__

1. Go to settings
2. Try to save
3. Click close button
4. You are at create profile page

__What happend__

After existing from settings, redirected back to create profile page where continue button is not working.

__Expected outcome__

Unintentional error.

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__
![image-2](https://cloud.githubusercontent.com/assets/3882707/15120757/859c08ac-1617-11e6-88c9-5d622ca87abe.png)

**Comment by ti-sedp** [comment]
Recreate all feature in settings page
