### ISSUE TITLE
Surfaces not clickable

### ISSUE THREAD

**Issue by justarrived-bugbash-1** [justarrived/just-match-frontend#263]
__Description__

In iOS on iPhone 5S, it's unintuitive that the surfaces for "What do you need help with?" and "Are you looking for part-time work?" are non-clickable.

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: The URL that the error occurred on.

__Error message__: The error message displayed, if any.

__Role__: Not logged in

__How to recreate it__

1. Goto http://justarrived.dev-machine.com/#/

__What happend__

Nothing happened when I clicked the pink or grey surface, just when I click the actual text "Upload your job here!".

__Expected outcome__

That when I click a surface on a touch-screen, it should work just like when I click the text.

__Browser (check what browser you're running at https://whatbrowser.org)__: Safari for iOS.
<img width="399" alt="screen shot 2016-05-09 at 18 56 53" src="https://cloud.githubusercontent.com/assets/19267466/15120834/d6724b2e-1617-11e6-802f-49b20430b0d7.png">

__Screenshot__

Take a screenshot of the error.

**Comment by ti-sedp** [comment]
Fixed can click all pink and black area
