### ISSUE TITLE
Free-text fileds do not adjust to the number of rows when it's filled

### ISSUE THREAD

**Issue by farshid12** [justarrived/just-match-frontend#265]
__Description__

Free-text fileds do not adjust to the number of rows when it's filled. When you placed the cursor in the next field, your text is hidden in the previous filed.

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: The URL that the error occurred on.

__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in
user
__How to recreate it__

1. Goto create profile
2. Click on "Arbetslivserfarenhet"
3. Type more rows than fits in the field.

__What happend__

__Expected outcome__
Expexted the field to adjust to the text, so I can read it when filling out this field and other fields.

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome/Firefox/Internet Firefox

__Screenshot__

Take a screenshot of the error.

**Comment by ti-sedp** [comment]
Fixed Add auto height to all textarea
