### ISSUE TITLE
UX issue: Seems I've applied for the job, and I cannot see the confirmation that I already applied for it.

### ISSUE THREAD

**Issue by yatinnova** [justarrived/just-match-frontend#267]
__Description__

UX issue: Seems I've applied for the job, and I cannot see the confirmation that I already applied for it.
__Severity__: Medium

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/jobs/115

__Error message__: The error message displayed, if any.

__Role__: user

__How to recreate it__

1. Apply for job, and button disappears

__What happend__

__Expected outcome__

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome
![1](https://cloud.githubusercontent.com/assets/17121324/15120879/18b0f90e-1618-11e6-8a93-3f5ec014b217.png)

__Screenshot__

Take a screenshot of the error.

**Comment by FivelFred** [comment]
Should display "Du har sökt uppdraget" / "You have applied"

**Comment by Ubonrat** [comment]
Fixed.
