### ISSUE TITLE
Yes and no buttons should be switched 

### ISSUE THREAD

**Issue by andreaskoenig** [justarrived/just-match-frontend#268]
__Description__

Short description of the problem

__Severity__:

_Chose one of the below:_

* Can not perform action
* Can perform with problem
* Can perform without problem but looks wrong
* Translation error
* New feature / suggestion

__URL__: The URL that the error occurred on.

__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in

__How to recreate it__

1. Goto ...
2. Click ...
3.

__What happend__

__Expected outcome__

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome/Firefox/Internet explorer version X

__Screenshot__

Take a screenshot of the error.

**Comment by FivelFred** [comment]
Design on purpose?
