### ISSUE TITLE
New arrived: Language skills, can't chose swedish

### ISSUE THREAD

**Issue by sofifridland** [justarrived/just-match-frontend#269]
__Description__

Group 3. 
When I fill in what language skills I have I can't select Swedish

__Severity__:

_Chose one of the below:_

* Can perform with problem

__URL__: The URL that the error occurred on.

http://justarrived.dev-machine.com/#/user

__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in

user

__How to recreate it__

1. Goto ... http://justarrived.dev-machine.com/#/user
2. Click ... Language skills, input field, type in swedish
3.

__What happend__

I couldn't select swedish 

__Expected outcome__

Expected to be able to chose swedish

__System__: Windows/OSX/Linux

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__
![ja bug can t chose swedish as language](https://cloud.githubusercontent.com/assets/19269855/15120926/5d98f9b8-1618-11e6-9379-cc88fc192f4f.JPG)

Take a screenshot of the error.

**Comment by ti-sedp** [comment]
https://just-match-api-staging.herokuapp.com/api_docs/1.0/languages/index.html
filter[en-name] cannot use to filter
it return no data all the time
ex.
https://just-match-api-staging.herokuapp.com/api/v1/languages?filter[en-name]=sw&page[number]=1&page[size]=50&sort=en-name

**Comment by buren** [comment]
@ti-sedp you're right it will currently only return on an exact match. 
Fixed in https://github.com/justarrived/just_match_api/pull/394

Will deploy soon

**Comment by buren** [comment]
https://just-match-api-staging.herokuapp.com/api/v1/languages?filter%5Ben-name%5D=sw&page%5Bnumber%5D=1&page%5Bsize%5D=50&sort=en-name

Returns the data you expect now
