### ISSUE TITLE
Missing link in conformation email

### ISSUE THREAD

**Issue by farshid12** [justarrived/just-match-frontend#270]
__Description__

Created a user and profile and received a confimation email, without a link to confirm my email

__Severity__:

_Chose one of the below:_

* Can not perform action

__URL__: The URL that the error occurred on.

__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in

__How to recreate it__

1. Go to create user
2. Go to create profile
3. Fill in all the information to recieve a confirmation email ...
4. Check email - no link?!

__What happend__

I checked my email, to confirm my email, so I can publish my profile. But I recieved no link in the message?

__Expected outcome__
Find a link in the message - to go to Just Arrived and confirm

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome/Firefox/Internet Firefox / gmail/ Iphone email client

__Screenshot__

Take a screenshot of the error.

**Comment by FivelFred** [comment]
Do we have back-end support for this?

**Comment by FivelFred** [comment]
@chris-sedp this was not in the scope but would be great if you could help us out. Please ping me on Slack to sort this out!

**Comment by buren** [comment]
This is not supported in the api, we've discussed this once or twice and last time I checked we said that we'd wait with this. I can if course implement it (its backend only), but we're not really using the confirmation for anything. 

@FivelFred if you want this open an issue at https://github.com/justarrived/just_match_api/issues

**Comment by FivelFred** [comment]
No. It is more a matter if copy as we tell the user they need to confirm. Let's save this one for later 


Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Jacob Burenstam <notifications@github.com> 
Datum: 05-20-2016  08:52  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Missing link in conformation
  email (#270) 

This is not supported in the api, we've discussed this once or twice and last time I checked we said that we'd wait with this. I can if course implement it (its backend only), but we're not really using the confirmation for anything. 

@FivelFred if you want this open an issue at https://github.com/justarrived/just_match_api/issues

**Comment by mblinovska** [comment]
In that case, it is probably better to remove this text "Confirm your email via the link in the email we have just sent you."

<img width="620" alt="screen shot 2016-05-22 at 15 43 03" src="https://cloud.githubusercontent.com/assets/18717885/15454262/e5395b36-2033-11e6-83de-644e6df62305.png">

**Comment by FivelFred** [comment]
Agree. Lets hide that text for now.

**Comment by chris-sedp** [comment]
Text removed
