### ISSUE TITLE
Yes and no buttons should be switched 

### ISSUE THREAD

**Issue by andreaskoenig** [justarrived/just-match-frontend#271]
<img width="1280" alt="skarmavbild 2016-05-09 kl 18 59 55" src="https://cloud.githubusercontent.com/assets/19269861/15120918/5424d19a-1618-11e6-8f89-b4ac06308b6e.png">
__Description__

Short description of the problem
It is more logical to have the yes-button on the left hand side 
__Severity__:

_Chose one of the below:_

* New feature / suggestion

__URL__: http://justarrived.dev-machine.com/#/arriver/job/115
__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in

__How to recreate it__

1. Goto ...
2. Click ...
3.

__What happend__

__Expected outcome__

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome
<img width="1280" alt="skarmavbild 2016-05-09 kl 18 59 55" src="https://cloud.githubusercontent.com/assets/19269861/15121026/bcd34118-1618-11e6-9a78-0af7dcc56015.png">

__Screenshot__

Take a screenshot of the error.

**Comment by Ubonrat** [comment]
Fixed.
