### ISSUE TITLE
Bad copy on hiring candidate functionality

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#272]
Team 4

__Description__

Bad copy on hiring candidate functionality. It says "du skickar en forfragan till Tom" but I haven't finished choosing Tom before I click on Send.

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/company/job/113/candidate/303

__Error message__: 

__Role__: Company user

__How to recreate it__

1. Click Menu
2. My Jobs
3. Click the job
4. Select candidate
5. Select a candidate
6. Anlita
7. You are at the desired page

__What happend__

Bad copy on hiring candidate functionality. It says "du skickar en forfragan till Tom" but I haven't finished choosing Tom before I click on Send.

__Expected outcome__

This message should be displayed after I accept the job.

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

![screenshot 2016-05-09 18 39 45](https://cloud.githubusercontent.com/assets/3882707/15121039/d19ae178-1618-11e6-8586-70fdbb386023.png)

**Comment by FivelFred** [comment]
Should say "You are about to send a request to xxxxx"
