### ISSUE TITLE
Missing language tags in created and saved profile

### ISSUE THREAD

**Issue by farshid12** [justarrived/just-match-frontend#273]
__Description__

Going back to profile to edit, language tags was missing from the profile. When creating the profile I selected three languges: Svenska, Farsi and Arabic. When I go back to edit my profile I find just Swedish.

__Severity__:

_Chose one of the below:_

* Can not perform action

__URL__: The URL that the error occurred on.

__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in

user

__How to recreate it__

1. Goto add several languges to your profile
2. Click Save
3. Go back to edit

__What happend__

Going back to profile to edit, language tags was missing from the profile. When creating the profile I selected three languges: Svenska, Farsi and Arabic. When I go back to edit my profile I find just Swedish.

__Expected outcome__

I expected my language skills to be saved!

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome/Firefox/Internet Firefox

__Screenshot__

Take a screenshot of the error.

**Comment by ti-sedp** [comment]
Fixed
