### ISSUE TITLE
Not understandable buttons at confirmed job page

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#274]
Team 4

__Description__

There are 2 not understandable buttons at confirmed job page.

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/arriver/job/113

__Error message__: 

__Role__: user

__How to recreate it__

1. Get confirmed for a job
2. Click My jobs
3. Click on the job
4. Look at the page

__What happend__

There are 2 not understandable buttons at confirmed job page.

__Expected outcome__

2 understandable buttons. What is this YES supposed to mean?

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

![screen shot 2016-05-09 at 19 07 53](https://cloud.githubusercontent.com/assets/3882707/15121208/bd3730dc-1619-11e6-979b-95974a6c11be.png)

**Comment by FivelFred** [comment]
See #281
