### ISSUE TITLE
New arrived: Don't get an email to verify my email as the message says.

### ISSUE THREAD

**Issue by sofifridland** [justarrived/just-match-frontend#277]
__Description__

Group 3. 
It says that I should get an email to verify my email when I register as a new arrived, but I don't get any. Although, I get an email before going to the second step in the registration just saying welcome.
__Severity__:

_Chose one of the below:_

* Can perform with problem

__URL__: The URL that the error occurred on.

http://justarrived.dev-machine.com/#/user

__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in

user

__How to recreate it__

1. Goto ...http://justarrived.dev-machine.com/#/user
2. Click ... nothing, but there is a message saying I should verify, but when I click "find jobs" I can.
3.

__What happend__

Didn't get an email

__Expected outcome__

Expected to get an email to verify my email.

__System__: Windows/OSX/Linux

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__
![ja didn t ge an email to confirm can still go forward though](https://cloud.githubusercontent.com/assets/19269855/15121281/1cec4454-161a-11e6-80fb-aafc1d165f7f.JPG)

**Comment by FivelFred** [comment]
#270 exists already
