### ISSUE TITLE
Error at confirmed job page

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#279]
Team 4

__Description__

At this page first click Yes and than send message, than I don't get to the chat page instead it displays another confirmation choice yes/no.

__Severity__:

_Chose one of the below:_

* Can not perform action

__URL__: http://justarrived.dev-machine.com/#/arriver/job/113

__Error message__: 

__Role__: user

__How to recreate it__

1. Get confirmed job
2. Go to my jobs
3. Go to the job
4. Click Yes
5. Click send message

__What happend__

At this page first click Yes and than send message, than I don't get to the chat page instead it displays another confirmation choice yes/no.

__Expected outcome__

Chat screen.

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

![screen shot 2016-05-09 at 19 12 32](https://cloud.githubusercontent.com/assets/3882707/15121289/2de21f9a-161a-11e6-94c7-d07746c09c4f.png)

**Comment by chris-sedp** [comment]
This one is fixed. Closing
