### ISSUE TITLE
I cannot see where to click in order to confirm that a job has been performed

### ISSUE THREAD

**Issue by andreaskoenig** [justarrived/just-match-frontend#281]
__Description__

Where do I click to confirm that I performed a job? I can click a button that says "yes" and then get to the right view. But it is not obvious nor intuitive. 

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/arriver/job/115
<img width="1280" alt="skarmavbild 2016-05-09 kl 19 05 27" src="https://cloud.githubusercontent.com/assets/19269861/15121305/4ba786dc-161a-11e6-8ab0-d99b2bd3d84c.png">

__Error message__: The error message displayed, if any.

__Role__: User

__How to recreate it__

1. Goto ...
2. Click ...
3.

__What happend__

__Expected outcome__

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

Take a screenshot of the error.

**Comment by FivelFred** [comment]
See #163, duplicate?
