### ISSUE TITLE
No notifications on the platform itself

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#282]
Team 4

__Description__

No notifications on the platform itself about accepted job confirmed, someone applying for a job, application being confirmed, etc. 

__Severity__:

_Chose one of the below:_

* New feature / suggestion

__URL__: http://justarrived.dev-machine.com

__Error message__:

__Role__: Company user / user

__How to recreate it__

1. Go to website
2. Do something

__What happend__

No notifications on the platform itself about accepted job confirmed, someone applying for a job, application being confirmed, etc. 

__Expected outcome__

Notifications.

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

**Comment by FivelFred** [comment]
Could be an idea to use sms for critical actions such as confirm that you will perform the job as applicant and confirm that the job is performed as job owner. What do you think @buren

**Comment by buren** [comment]
@FivelFred seems like a great idea. That way it wouldn't cost too much and we can add text message notifications gradually.

**Comment by buren** [comment]
Created an issue in the api to track the sms feature: https://github.com/justarrived/just_match_api/issues/423

**Comment by buren** [comment]
justarrived/just_match_api#423 is closed, so I'm closing this too :)
