### ISSUE TITLE
New Arrived & Company; request for notification if someone sends me a message

### ISSUE THREAD

**Issue by sofifridland** [justarrived/just-match-frontend#283]
__Description__

When I get a message I don't get any notification for either the company or new arrived. I have to really go in to the job and look which could be hard when you have many applicants or many jobs.

__Severity__:

_Chose one of the below:_

* New feature / suggestion

__URL__: The URL that the error occurred on.

http://justarrived.dev-machine.com/#/arriver/job/114
__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in

__How to recreate it__

1. Goto ...
2. Click ...
3.

__What happend__

__Expected outcome__

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

Take a screenshot of the error.

**Comment by FivelFred** [comment]
See #261
