### ISSUE TITLE
Label is wrong at account details

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#284]
Team 4

__Description__

Label for bank says Bank Swedbank but it should be Bank Name.

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/arriver/job/120

__Error message__: 

__Role__: user

__How to recreate it__

1. Apply for a job
2. Get accepted by a job
3. Go to my jobs
4. Provide answer
5. Yes
6. Fill out account details

__What happend__

Label for bank says Bank Swedbank.

__Expected outcome__

 it should be Bank Name.

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

![screen shot 2016-05-09 at 19 21 52](https://cloud.githubusercontent.com/assets/3882707/15121535/689211a8-161b-11e6-8aef-012f56154433.png)

**Comment by Ubonrat** [comment]
Fixed.
