### ISSUE TITLE
"Submit for review" in job post redirects to a half loaded page with no info. 

### ISSUE THREAD

**Issue by ladi00** [justarrived/just-match-frontend#285]
__Team 4__

__Description__

I pushed the button "Submit for review" in job post. it redirected me to this page. it does not load and looks like an error. 

__Severity__:

_Chose one of the below:_

* Can not perform action

__URL__: http://justarrived.dev-machine.com/#

__Error message__: 

__Role__: user 

__How to recreate it__

1. Click on a job
2. click on "Submit for review"

__What happend__

I pushed the button "Submit for review" in job post. it redirected me to this page. it does not load and looks like an error. 

__Expected outcome__

expected to leave a review 

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

![image](https://cloud.githubusercontent.com/assets/10079523/15121540/6de9eda6-161b-11e6-835d-2c838513f51c.png)

Take a screenshot of the error.

**Comment by FivelFred** [comment]
See #280

**Comment by FivelFred** [comment]
See #248
