### ISSUE TITLE
Account details should include Clearing, Account / BIC and IBAN

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#286]
Team 4

__Description__

Account number and IBAN number is not same thing. 

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/arriver/job/120

__Error message__: 

__Role__: user

__How to recreate it__

1. Apply for a job
2. Get accepted by a job
3. Go to my jobs
4. Provide answer
5. Yes
6. Try to fill out account details

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

![screen shot 2016-05-09 at 19 21 52](https://cloud.githubusercontent.com/assets/3882707/15121593/9555ab28-161b-11e6-8c2c-4d72bc6363c3.png)

**Comment by FivelFred** [comment]
This is not true. It should not be removed. Sorry about this @ti-sedp but could you take it back?

**Comment by Ubonrat** [comment]
Fixed.
