### ISSUE TITLE
Datepicker functionality on job creation screen

### ISSUE THREAD

**Issue by sofifridland** [justarrived/just-match-frontend#287]
__Description__

Group 3
When entering dates for a job, it would be better to have a datepicker functionality.

__Severity__:

_Chose one of the below:_

* New feature / suggestion

__URL__: The URL that the error occurred on.

/job/create

__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in

Company user

__How to recreate it__

1. Goto /job/create
2. Click one of the dates (either FROM or TO)

__What happend__

Nothing

__Expected outcome__

Datepicker tool to popup

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome/Firefox/Internet explorer version X

Chrome iOS

__Screenshot__

![jadatepicker](https://cloud.githubusercontent.com/assets/19269855/15121639/c5b8f2b6-161b-11e6-8428-ea07d32a1a9e.PNG)

**Comment by Ubonrat** [comment]
Fixed so it shows datepicker keyboard on mobile
