### ISSUE TITLE
Validations on account details

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#289]
Team 4

__Description__

Account details does not have any validations. There is a standard on those fields so it should be checked.

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/arriver/job/120

__Error message__: 

__Role__: user

__How to recreate it__

1. Apply for a job
2. Get accepted by a job
3. Go to my jobs
4. Provide answer
5. Yes
6. Try to fill out account details

__What happend__

Account details does not have any validations.

__Expected outcome__

There is a standard on those fields so it should be checked.

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

![screen shot 2016-05-09 at 19 24 54](https://cloud.githubusercontent.com/assets/3882707/15121709/17c6e0ae-161c-11e6-8242-c571b30c887c.png)

**Comment by FivelFred** [comment]
Wait with this one. Validations are risky in this context...

**Comment by buren** [comment]
These validations are now available in the API.

The only thing that this form must do is display those validation errors returned by that API..
