### ISSUE TITLE
Opening a page in new tab requires login

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#290]
Team 4

__Description__

Opening a page in new tab requires login

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/

__Error message__: 

__Role__: Company user / user

__How to recreate it__

1. Login to website
2. Open a page in new tab
3. You'll see you need to login again

__What happend__

Opening a page in new tab requires login

__Expected outcome__

Opening a page in new tab should not require login

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

**Comment by ti-sedp** [comment]
Fixed
