### ISSUE TITLE
Job languages are preselected

### ISSUE THREAD

**Issue by sofifridland** [justarrived/just-match-frontend#291]
__Description__

Group 3
On the job approval screen, the languages for said job have been prefilled.

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: The URL that the error occurred on.

job/approve

__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in

company user

__How to recreate it__

1. Goto job/approve
2. Note the languages listed here

__What happend__

Languages listed are Eng, Svenska, Arabiska

__Expected outcome__

There was no option to add languages to the job so I didn't expect anything here

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome/Firefox/Internet explorer version X

Chrome iOS

__Screenshot__

![img_0923](https://cloud.githubusercontent.com/assets/19269855/15121837/9c66c6b2-161c-11e6-8526-ef8c8db1da75.PNG)

**Comment by FivelFred** [comment]
This is a bug due to a fault in the design breif. @buren do we have support to log language preferences for a job? If so, it should be implemented.

**Comment by buren** [comment]
@FivelFred do you mean that the Job owner is supposed to be able to say that they want someone that can speak a certain language(s)?

**Comment by FivelFred** [comment]
Yes @buren


Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Jacob Burenstam <notifications@github.com> 
Datum: 05-10-2016  21:08  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Job languages are preselected
  (#291) 

@FivelFred do you mean that the Job owner is supposed to be able to say that they want someone that can speak a certain language(s)?

**Comment by ti-sedp** [comment]
Removed job language section

**Comment by chris-sedp** [comment]
@FivelFred shall we remove the language section ?

**Comment by FivelFred** [comment]
No. The user should be able to choice language. I think people reacted in the bug testing about that it was prefilled but if it is prefilled with the chosen system language, that is fine!
Fredric 
Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Christopher <notifications@github.com> 
Datum: 05-17-2016  09:22  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Job languages are preselected
  (#291) 

@FivelFred shall we remove the language section ?

**Comment by chris-sedp** [comment]
@FivelFred I see it's already removed quite long ago. Today we don't have any language selection when creating a job.

**Comment by FivelFred** [comment]
Oh sorry. Misunderstanding from my side. You are right @buren

**Comment by chris-sedp** [comment]
So closing now then.
