### ISSUE TITLE
Cannot close side menu by clicking outside of it

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#292]
__Description__

When I open the side menu, I cannot close it by clicking anywhere outside the menu.

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/

__Error message__: 

__Role__: Company user / user / Not logged in

__How to recreate it__

1. Open right menu
2. Try to close it by clicking outside of menu

__What happend__

When I open the side menu, I cannot close it by clicking anywhere outside the menu.

__Expected outcome__

Menu should be closed after I click outside of the menu.

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

**Comment by Ubonrat** [comment]
Fixed.
