### ISSUE TITLE
Amount of hours are unlimited 

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#294]
Team 4

__Description__

I can create a job for one day but I can set more than 24 hours for one day job.

__Severity__:

_Chose one of the below:_

* Can perform with problem

__URL__:  http://justarrived.dev-machine.com/#/job/create

__Error message__: 

__Role__: Company user

__How to recreate it__

1. Create a job

__What happend__

I can create a job for one day but I can set more than 24 hours for one day job.

__Expected outcome__

Hours must not be unlimited.

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

![screen shot 2016-05-09 at 19 34 10](https://cloud.githubusercontent.com/assets/3882707/15122011/67cd1c34-161d-11e6-9048-ee4b20e8bbcc.png)

![screen shot 2016-05-09 at 19 36 54](https://cloud.githubusercontent.com/assets/3882707/15122034/78e8c126-161d-11e6-9962-110c8c4d82f5.png)

**Comment by Ubonrat** [comment]
I tested and it seems correct, when you click "approve" then it will redirect back to the form page with error message.

![capture](https://cloud.githubusercontent.com/assets/18320820/15245930/b9247e56-1933-11e6-8142-811bb4de256b.PNG)
