### ISSUE TITLE
When job is created and I try to select wage, same wages appear multiple times

### ISSUE THREAD

**Issue by ladi00** [justarrived/just-match-frontend#295]
__Team 4__

__Description__

When job is created and I try to select wage, same wages appear multiple times
__Severity__:

_Chose one of the below:_

* Can perform with problem

__URL__: http://justarrived.dev-machine.com/#/job/create

__Error message__: 

__Role__: Company user 

__How to recreate it__

1. Go to create a job
2. Click wages

__What happend__

When job is created and I try to select wage, same wages appear multiple times

__Expected outcome__

expected to have wages drop down menu without repetitions of the same number

__Browser (check what browser you're running at https://whatbrowser.org)__: Safari

__Screenshot__
![image](https://cloud.githubusercontent.com/assets/10079523/15122105/c6e4fdb8-161d-11e6-8097-e2b5da7d84e4.png)

Take a screenshot of the error.

**Comment by buren** [comment]
This is actually because the database seed task has been run multiple times on the staging machine so this is actually not a bug in the frontend, but due to duplicate data in the API.
