### ISSUE TITLE
Number of hours is greater than 0.5, but still throwing an error

### ISSUE THREAD

**Issue by sofifridland** [justarrived/just-match-frontend#296]
__Description__

When creating a job, the number of hours was set to 2, but when going to the next step it threw back an error saying that it must be more than 0.5 hours per day.

__Severity__:

_Chose one of the below:_

* Can not perform action

__URL__: The URL that the error occurred on.

job/create

__Error message__: The error message displayed, if any.

"must be at least 0.5 hour(s) per day"

__Role__: Company user / user / Not logged in

Company user

__How to recreate it__

1. Goto job/create 
2. Click "Number of hours" and enter 2 and then try and click on Next Step

__What happend__

Wouldn't let me continue with more than 0.5 hours, despite entering 2.

__Expected outcome__

To be able to continue having entered more than 0.5 hours

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome/Firefox/Internet explorer version X

Chrome iOS

__Screenshot__

![img_0924](https://cloud.githubusercontent.com/assets/19269855/15122124/e553f81c-161d-11e6-9d08-c3344a9b3f02.PNG)

**Comment by FivelFred** [comment]
Clearly the number of days is more than 4 days in this instance. Faulty report?
