### ISSUE TITLE
Company user profile look the same as the user profile

### ISSUE THREAD

**Issue by farshid12** [justarrived/just-match-frontend#297]
__Description__
we created a company user profile, and when we looked back to the created profile we realised that the profile was just the same. It lacks bank details and personalnumber text. 

Short description of the problem

__Severity__:

_
* Can perform with problem

* Translation error
* New feature / suggestion

__URL__: The URL that the error occurred on.

__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in
Company user
__How to recreate it__

1. Goto  menu 
2. Click on the profile picture
3. The copy and the design is the same as for both users.

__What happend__

__Expected outcome__
Different copy targeting the company user

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome/Firefox/Internet Firefox

__Screenshot__

Take a screenshot of the error.

**Comment by FivelFred** [comment]
See #285
