### ISSUE TITLE
Cant see the name of job while editing it

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#298]
Team 4

__Description__

Cant see the name of job while editing it

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/company/job/122/candidate/317

__Error message__: 

__Role__: Company user

__How to recreate it__

1. Create a job
2. Let someone apply for the job
3. Accept application
4. You get the page where you cannot see anything

__What happend__

Cant see the name of job while editing it

__Expected outcome__

To be able to see name of the job

__Browser (check what browser you're running at https://whatbrowser.org)__: Safari

__Screenshot__

![screen shot 2016-05-09 at 19 39 49](https://cloud.githubusercontent.com/assets/3882707/15122173/16219fc6-161e-11e6-97f9-15453b0f0f55.png)

**Comment by chris-sedp** [comment]
This is according to current flow and design. You have reached the candidate page for the user who you just accepted for the job and can start a chat with him. 

@FivelFred this may not be the best UX so we should look into it. At the same time we should not add to many changes this late in the project. What is your opinion on this?

**Comment by chris-sedp** [comment]
Removing the meddelande button for now and closing.

**Comment by chris-sedp** [comment]
Meddelanden moved to a separate tab
