### ISSUE TITLE
Submit for review is not working

### ISSUE THREAD

**Issue by furkan3ayraktar** [justarrived/just-match-frontend#300]
Team 4

__Description__

Submit for review is not working when I click that button.

__Severity__:

_Chose one of the below:_

* Can not perform action

__URL__: http://justarrived.dev-machine.com/#/jobs/122

__Error message__: 

__Role__: user

__How to recreate it__

1. Go to jobs
2. Click one job
3. Click on submit for review

__What happend__

Clicked submit for review and nothing happened.

__Expected outcome__

__Browser (check what browser you're running at https://whatbrowser.org)__: Safari

__Screenshot__

![screen shot 2016-05-09 at 8 04 17 pm](https://cloud.githubusercontent.com/assets/3882707/15122987/da1fceae-1621-11e6-8d4f-caaabe98c20c.png)

**Comment by FivelFred** [comment]
See #285
