### ISSUE TITLE
Title of jobs in rolling list on front-page are overlapping eachother if text is long

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#304]
__Description__

When a job has a to long word in the beginning of the header it overlapps the other jobs. 

__Severity__:

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/

__Role__: Not logged in

__How to recreate it__

1. Post a job with a long name / long first word like "The-dream-job-of-your-life"
2. Go to starting page
3. Adjust width of browser

__What happend__

Overlap 

__Expected outcome__

That the application would truncate the name

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome 50

__Screenshot__

![screenshot](https://cloud.githubusercontent.com/assets/16607246/15145753/c092f16e-16b7-11e6-9048-8a02904bf451.PNG)

**Comment by Ubonrat** [comment]
Fixed.
