### ISSUE TITLE
Not the correct Q&A in the application 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#305]
__Description__

Dummy Q&A are displayed instead of the ones specified... 

__Severity__:

* Can not perform action

__URL__: http://justarrived.dev-machine.com/#/faq

__Role__: Not logged in

__How to recreate it__

1. Go to start-page
2. Click meny
3. Click Q&A (frågor och svar)

__Expected outcome__

That the correct Q&A are displayed. See Just Arrived copy.xlsx on google drive. 

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome 50
![q a](https://cloud.githubusercontent.com/assets/16607246/15145991/0c5c5d14-16b9-11e6-8266-eb980b977392.PNG)

__Screenshot__

Take a screenshot of the error.

**Comment by buren** [comment]
This is not the frontends "fault", the faqs is fetched from the api
