### ISSUE TITLE
Contact form can be dragged out sideways to far

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#306]
__Description__

It is possible to drag out the contact form field sideways beyond the browser. 

__Severity__:

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/contact/new

__How to recreate it__

1. Contact
2. Drag the low left corner of message to the right 

__Expected outcome__

That the input field can not be expanded further to the right than the broswer is wide. 

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome 50 
![contact form](https://cloud.githubusercontent.com/assets/16607246/15146639/de47dff8-16bc-11e6-8fc3-dc7e394a41c7.PNG)

__Screenshot__

Take a screenshot of the error.

**Comment by chris-sedp** [comment]
added a max-width of 100% for textarea
