### ISSUE TITLE
Can not choose language in the application (more than swedish and english)

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#307]
__Description__

Arabic (ar), Persian (fa), Dari (fa_AF), Tingrinja (ti), Pushto (ps), Kurdish (ku) are not availible.  

__Severity__:

* Can not perform action

__URL__: http://justarrived.dev-machine.com/#/

__How to recreate it__

1. Click pink symbol for language next to meny

__Expected outcome__

To get the opportunity to choose between all available languages (in Transifex) i.e. the following;

Arabic (ar), Persian (fa), Dari (fa_AF), Tingrinja (ti), Pushto (ps), Kurdish (ku)

**Comment by chris-sedp** [comment]
In the current code we are using:
languages?filter[system_language]=true

This resource only returns swedish and english.

**Comment by buren** [comment]
@chris-sedp you're absolutely right :) 

I've updated the backend, so now it lists all languages.

<img width="377" alt="screen shot 2016-05-11 at 19 38 58" src="https://cloud.githubusercontent.com/assets/922411/15190420/13ebf312-17b0-11e6-926c-016ea60a55a4.png">
