### ISSUE TITLE
Should return http status 404, when page not found

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#313]
Currently a 404 page is implemented, but we should also return a HTTP 404 status, when the page is missing. This can't be completed until the final production environment has been setup and decided.

**Comment by FivelFred** [comment]
how does this one look?

**Comment by FivelFred** [comment]
Do we need to make some design?

**Comment by buren** [comment]
Nothing thats design related..

**Comment by FivelFred** [comment]
Please elaborate in what we need

**Comment by buren** [comment]
The frontend now responds with 404 if the requested page doesn't exist.
