### ISSUE TITLE
There is no way to see the location of a job

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#320]
__Description__

There is currently no way to see the adress of a job. 

__Severity__:

* Can perform with problem

__URL__: http://justarrived.dev-machine.com/#/arriver/job/132

__Role__: user 

__How to recreate it__

1. Log in as user
2. Apply for a job
3. Get accepted
![Uploading there is no adress.png…]()
![Uploading there is no adress.png…]()

4. Look at your jobs

__What happend__

No information about the job availible 

__Expected outcome__

To get the full adress displayed in "Mina uppdrag"

Take a screenshot of the error.
![Uploading there is no adress.png…]()

**Comment by chris-sedp** [comment]
@buren We need to get the street attribute in this resource /api/v1/jobs

**Comment by buren** [comment]
@chris-sedp you do if you're logged in as the owner or the accepted applicant the API will return those fields.

For example

```
curl -H 'Authorization: Token token=b0b5e099-7529-44e7-960b-fc9e8e3037fe' \
     -X GET https://just-match-api-staging.herokuapp.com/api/v1/jobs/109 \
     -s | python -mjson.tool
```

returns `street`, exact `longitude`, `latitude`.

**Comment by chris-sedp** [comment]
@buren so correct. I have implemented this one for both the list and the detail view for the job. Im closing this one but we may have some look to make the styling a bit more appealing.

**Comment by buren** [comment]
:+1:
