### ISSUE TITLE
Drop down list of location - for filtering location as job applicant

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#323]
Would be nice to have a dropdown list of location when creating a job so we can use that as a filter option for the job applicants. Future feature, post launch?

**Comment by buren** [comment]
@FivelFred I think you and I need to discuss how this would work and would be implemented a little bit before adding it to the frontend.

**Comment by FivelFred** [comment]
I think this could more important than we imagine. Not only from a product perspective but also from a concept perspective. If we launch all over Sweden at the same time the platform will not work as it will not be able to match applicants with jobs as they are to spread out. We should restrict the usage to a few citites like Stockholm, Gothenburg and Malmö. Let us discuss this on the hand over @buren
