### ISSUE TITLE
To change password, you would need to enter old one and new twice

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#324]
Should not be possible to change password without entering the old password before. In addition it should ask for the new password twice. Decrease the chances of typing errors and improves security.

![skarmavbild 2016-05-19 kl 13 54 20](https://cloud.githubusercontent.com/assets/16607246/15392715/49d0a404-1dc9-11e6-8943-e3c4d7dbc6f6.png)

**Comment by ti-sedp** [comment]
Fixed
