### ISSUE TITLE
"Apply for job" button should dislodge over "More jobs"

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#325]
![capture6](https://cloud.githubusercontent.com/assets/16607246/15218785/ad438956-1861-11e6-9d42-ab774c8bf2af.PNG)

__Description__

When scrolling down the apply for job button continues down instead of dislodging over more jobs. 

__Severity__:

* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/jobs/130

__Role__: User

__How to recreate it__

1. Goto find jobs
2. Click on a job
3. Decrease browser size until you get full screen button for "Apply for job"
3. Scroll down over More jobs

__What happend__

The button continues 

__Expected outcome__

The button would dislodge.

__Screenshot__

Take a screenshot of the error.

**Comment by Ubonrat** [comment]
Fixed.
