### ISSUE TITLE
Add Semantix logo and translators name with a short thanks message

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#343]
Would like to add Semantix logo and names of people who have contributed with translation under the language options. Should be a short text saying; 

"The translations have been performed as pro-bono contribution to the project by

Semantix (loggan)
Farshid Fadaee
Nick Chipperfield
Hans-Erik Täpp"

![capture9](https://cloud.githubusercontent.com/assets/16607246/15246777/bc5d71be-190f-11e6-994c-cbdc7d293255.PNG)

![semantix logo color](https://cloud.githubusercontent.com/assets/16607246/15246791/d6d7817e-190f-11e6-919d-b52c7a166230.png)

![semantix logo](https://cloud.githubusercontent.com/assets/16607246/15246792/d6dab38a-190f-11e6-9424-271cd386c3dc.png)

**Comment by FivelFred** [comment]
Need to add stockholm skrivarbyrås logo as well. 

https://mail.google.com/mail/u/0/?ui=2&ik=5f74808565&view=att&th=154c370925215169&attid=0.1&disp=safe&realattid=f_iocqhhhr0&zw

**Comment by FivelFred** [comment]
Change Semantix logo to this one (below in white); 

![semantix_logo_orange_nobackground_orangepil_horisontal_rgb](https://cloud.githubusercontent.com/assets/16607246/15358676/cc8f620a-1d05-11e6-877e-a7c8913e846a.png)

**Comment by lenaar** [comment]
done

**Comment by buren** [comment]
Close by #447
