### ISSUE TITLE
Add cookies banner

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#348]
We need to add a banner stating the terms and conditions for cookies. Below is the specification set by our legal team:

Information om cookies bör finnas separat. Det kommer att finnas ett avsnitt om cookies i er privacy policy som användaren godkänner. Sedan bör ni även ha information om cookies separat från detta och en banner med texten "Vi använder cookies. Läs mer. Jag förstår." (ungefär) där "Läs mer" leder till informationssidan och ett klick på "Jag förstår" leder till att bannern inte visas igen.

**Comment by buren** [comment]
> Information om cookies bör finnas separat. Det kommer att finnas ett avsnitt om cookies i er privacy policy som användaren godkänner. Sedan bör ni även ha information om cookies separat från detta och en banner med texten "Vi använder cookies. Läs mer. Jag förstår." (ungefär) där "Läs mer" leder till informationssidan och ett klick på "Jag förstår" leder till att bannern inte visas igen.

@FivelFred I guess that content would need to be translated?

If so we need to

1. Add it to the main (a.k.a source file) translation to Transifex
2. Translate the content @ Transifex
3. Pull the translations and push them to GitHub

**Comment by buren** [comment]
@pstenstrm is this something that you might want to build? 👼

**Comment by camillaryd** [comment]
This is the design for the cookie bar. The text is just dummy text, but you see the color and the layout. Find it on here on Zeplin for more details: https://zpl.io/5VgFT

![cookie bar](https://cloud.githubusercontent.com/assets/19821275/16799909/215883e8-48f3-11e6-9d95-81106b55a92d.png)

**Comment by pstenstrm** [comment]
I can take a look. I'll have to figure out how to do it in angular, but in plain javascript it's trivial.

Is there any documentation about how to work with copy?

**Comment by camillaryd** [comment]
We can use this text for now 

"By using the justarrived.se website, you agree to the use of cookies by us and third parties to enhance your experience. For more information, or to change your cookie settings.

Link: More about Cookies

Button: Accept
