### ISSUE TITLE
Hard coded confirmation time in ArriverJobCtrl

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#353]
__Description__

In `ArrivedJobCtrl` the value `waitMaxMinutes` is hardcoded to 18 hours. This value doesn't need to be hard coded but can be calculated from the date-time value, [`will-perform-confirmation-by`](http://localhost:3000/api_docs/1.0/job_users/index.html), the arrived must set `will-perform` to true ([see docs](http://localhost:3000/api_docs/1.0/job_users/index.html)) before that date-time.

[current code](https://github.com/justarrived/just-match-frontend/blob/74f3884cbf3efaa461b32d174c79bafa418f3298/src/app/common/controllers/ArriverJobCtrl.js#L139):

```js
// src/app/common/controllers/ArriverJobCtrl.js#L139
this.maxWaitMinutes = 1080; // 18 hours
```

This means that if the confirm time can differ between frontend/backend..

**Comment by FivelFred** [comment]
I think this is implemented?
