### ISSUE TITLE
No option to translate job description and job name to language of choice

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#384]
![skarmavbild 2016-05-17 kl 10 49 58](https://cloud.githubusercontent.com/assets/16607246/15316432/3fbcf6f0-1c1d-11e6-8aa1-d38201ff6b1d.png)

All user generated content should be able to translate with google translate (and an option to view original).

**Comment by FivelFred** [comment]
According to Skype call with @chris-sedp it will work as follows;

The text will be translated through google api if the common language is different from what the user generated text was written. It will then translate to the common language. The user will get the alternative to press "See original" to see the original text. This feature needs to exist in all user generated input. 

For jobs it will be by the job title and job description. And at the sections More Jobs / New Jobs / Find Jobs (xx). 

For Profile and References it will be one "See original" above the texts.

**Comment by chris-sedp** [comment]
Still working on this one but have it ready very soon. You can test on the job-detail page in a few minutes. Right now it is a texts link but we will change to an icon later today. It will look cleaner.
