### ISSUE TITLE
Price of job and salary of job should be different 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#385]
We need to have three price levels for companies they can choose from; 139, 159, 179 SEK excl. VAT (needs to be simple to alter). When previewing the job it needs to clear that the job will be advertised with a price but the cost will be something different (due to social fees, taxes etc.)

This will result in a different salary then the price chosen by the company as social fees, taxes and insurance needs to be payed. The conversion key is provided by Frilans Finans (right @buren). If it is not provided by Frilans Finans it needs to be hard-code. The amount the salary is should be displayed on the job.  

We need to figure this out prior to launch on Monday (the 23rd of May).

![skarmavbild 2016-05-17 kl 11 01 01](https://cloud.githubusercontent.com/assets/16607246/15316767/b826cf20-1c1e-11e6-8f6b-eb8bdf4e7ffc.png)

![skarmavbild 2016-05-17 kl 11 00 33](https://cloud.githubusercontent.com/assets/16607246/15316768/b82786e0-1c1e-11e6-971c-bef72b6cd08c.png)

**Comment by buren** [comment]
@FivelFred you can edit/update add "hourly pays" in the admin interface: https://just-match-api-staging.herokuapp.com/admin/hourly_pays

**Comment by FivelFred** [comment]
@buren will create an additional resource in the backend for this which @chris-sedp will be able to access and connect to the front-end where the sum is displayed. @buren please refer @chris-sedp to the right resource to make it easy for him

**Comment by buren** [comment]
Supported in the API now: https://just-match-api-staging.herokuapp.com/api_docs/1.0/hourly_pays/index.html now returns `rate-with-fees`

**Comment by chris-sedp** [comment]
Ok. I will jump on this one directly after the translation.

**Comment by FivelFred** [comment]
Great. Thanks Christopher for being agile and fast when we need it the most 
Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Christopher <notifications@github.com> 
Datum: 05-20-2016  12:30  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Price of job and salary of job
  should be different  (#385) 

Ok. I will jump on this one directly after the translation.

**Comment by FivelFred** [comment]
This seems to work. What would it take to be able to write out both the cost and the the salary in the list? @chris-sedp @buren

**Comment by buren** [comment]
@FivelFred a fairly minor change in the frontend.
