### ISSUE TITLE
Update picture on starting page

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#387]
Update starting page of application with new photos. Will be possible on Thursday when the marketing team has produced them. 

![skarmavbild 2016-05-17 kl 11 33 25](https://cloud.githubusercontent.com/assets/16607246/15317835/73463a30-1c23-11e6-81d5-5670abeec255.png)

**Comment by FivelFred** [comment]
![0afea9_36f750e634474fb39649183330bed581](https://cloud.githubusercontent.com/assets/16607246/15353932/94acc306-1ceb-11e6-9aae-655af08b4035.png)

**Comment by FivelFred** [comment]
![0afea9_18c8336362184117b091d18f9c529d5f](https://cloud.githubusercontent.com/assets/16607246/15353937/9b82b230-1ceb-11e6-8589-3a630d62347e.jpg)

**Comment by FivelFred** [comment]
The photo delivery will be delayed (next Tuesday) but maybe we could use this one for now...

**Comment by buren** [comment]
License OK?

**Comment by FivelFred** [comment]
Yes. For the picture we uploaded we have rights. 
Fredric 
Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Jacob Burenstam <notifications@github.com> 
Datum: 05-18-2016  12:28  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Author <author@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Update picture on starting page
  (#387) 

License OK?

**Comment by lenaar** [comment]
Added picture as a second slide of hero slider
