### ISSUE TITLE
Job category list must flag jobs not allowed (according to Frilans Finans indexation) 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#406]
There are a number of job categories that are not allowed to be mediated through Frilans Finans service (due to insurance reasons). 

The user should be able to see thoose categories but get information about that they are not allowed and that it is against the terms of the plattform to put up jobs that belong to thoose categories. 

One idea is to have them in red with a text after that says (not allowed) and if they are selected a text will come up which explains why and the importance of not posting jobs of that category. 

![kategorilistning](https://cloud.githubusercontent.com/assets/16607246/15363903/b73f864a-1d1a-11e6-9a56-1c5d5904979d.PNG)

**Comment by FivelFred** [comment]
@buren any input on how this could be made?

**Comment by buren** [comment]
@FivelFred Yeah its mostly in my to provide the data for this. Personally I think we should just not list them. I know it's been discussed that people would then perhaps chose another category, there is over 8 thousand of them so I think that people will anyway.

**Comment by FivelFred** [comment]
Ok, for now do not display the non allowed jobs but we need to sort this out asap after launch @buren

**Comment by buren** [comment]
Yeah, just checked FFs API and currently they don't return that information for professions... 😞

**Comment by buren** [comment]
Ok, so FF has come through and returns the correct data. I've also updated the API to only return categories that are insurable.

**Comment by buren** [comment]
Fixed by the API just returning categories that can be insured.
