### ISSUE TITLE
Settings page for job performer shows wrong data

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#413]
Under settings, bank details it shows the wrong details. It shows telephone number under BIC number. 
![skarmavbild 2016-05-19 kl 11 05 18](https://cloud.githubusercontent.com/assets/16607246/15388337/bc1272b2-1db1-11e6-8314-bd1160fe9115.png)

**Comment by buren** [comment]
Fyi we don't store any account details locally in our database, those details are stored by frilans-finans

**Comment by ti-sedp** [comment]
It autocomplete fill in from browser
Fixed
