### ISSUE TITLE
Settings page does not have a edit button

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#414]
There is no edit button and it is unclear what I can change and how. Should be an edit button that can be clicked which enables editing. That button should then change to save. When pressing save it should go back to saying edit. 

Corporate user. Logged in.

**Comment by FivelFred** [comment]
To be a bit more elaborate. The user should have the option to edit settings and profile (as job applicant). To do this the user should need to press a button Edit. This will "activate" the alternative to edit input field. To save the changes the user needs to click Save. See sketch below:

![edit profile](https://cloud.githubusercontent.com/assets/16607246/16224817/07f4afc2-37a4-11e6-84cb-77ae4356b93f.jpg)

**Comment by ti-sedp** [comment]
Fixed 
click edit button to enable save feature in setting and profile page

**Comment by FivelFred** [comment]
Can you push this to staging?
