### ISSUE TITLE
It is possible to add language in profile but it does not show up for the person hiring

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#417]
As logged in corporate user, when you preview a candidate you can not see their language skills although they have entered them. Should be possible. 

![skarmavbild 2016-05-19 kl 11 29 09](https://cloud.githubusercontent.com/assets/16607246/15389034/24c89842-1db5-11e6-9c7a-247a729f02f5.png)

**Comment by Ubonrat** [comment]
Fixed.
