### ISSUE TITLE
A user without review gets an automatic rating of 4

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#419]
Although the user has no references/ rating he still has 4 stars when looking at the candidate as a corporate user. Not sure why this is. 

![skarmavbild 2016-05-19 kl 11 37 21](https://cloud.githubusercontent.com/assets/16607246/15389309/808ad3e2-1db6-11e6-9404-d62d35303487.png)

**Comment by ti-sedp** [comment]
Not sure i get data from api.
For example i call user rating api for user id 284, this use have 2 jobs that still wait owner to hire. 
but api return average score 4.14xxx and data come with other user rating too

![2559-05-22_04h40_57](https://cloud.githubusercontent.com/assets/16758634/15450964/656daae4-1fd7-11e6-982a-adaa31f612e9.png)

**Comment by buren** [comment]
Actually I discovered a bug in the API that it was returning ratings for other users 😳 

I've already deployed a fix for it. So now if there are now ratings for a user the API will return `average-score = null`

**Comment by FivelFred** [comment]
Thanks for digging into this Wiratti and thanks Jacob for sorting it out.

**Comment by ti-sedp** [comment]
Fixed
