### ISSUE TITLE
When you choose a candidate you should be redirected by to the view for that job

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#421]
Now you come back to the profile instead of to the job.

![skarmavbild 2016-05-19 kl 11 55 32](https://cloud.githubusercontent.com/assets/16607246/15389755/b72e49f4-1db8-11e6-9e68-89b6a4f7cd6a.png)

**Comment by ti-sedp** [comment]
Fixed

**Comment by FivelFred** [comment]
@ti-sedp have you added more urls (one for each tab) or how did you implement it?

**Comment by ti-sedp** [comment]
It's the same url but force it active reference when come from choose candidate page
