### ISSUE TITLE
In archive (arkiv) the corporate user is asked to give rating despite that it has already been given

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#424]
In archive (arkiv) the corporate user is asked to give rating despite that it has already been given. 

Should show given grade and comment. 

How it looks for the corporate user:
![skarmavbild 2016-05-19 kl 12 03 14](https://cloud.githubusercontent.com/assets/16607246/15390067/0b0db540-1dba-11e6-9c60-4d4e034aa13c.png)

Despite already given grade:
![skarmavbild 2016-05-19 kl 12 01 45](https://cloud.githubusercontent.com/assets/16607246/15390068/0c9c6adc-1dba-11e6-8ff9-a1ae62ef22ee.png)

**Comment by buren** [comment]
Interesting.. I haven't really thought about this, so I don't think that this information is possible to get from the API. I'll have to look into it.

**Comment by buren** [comment]
I spoke to early it is possible, however it's a bit awkward to get the information see


https://just-match-api-staging.herokuapp.com/api_docs/1.0/user_ratings/index.html

I'll add the possibility to filter by job id

**Comment by buren** [comment]
This is now fixed. You can filter on job id now

**Comment by ti-sedp** [comment]
Fixed
