### ISSUE TITLE
Should be possible to apply for job without being logged in (will redirect you to sign-up or log-in)

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#425]
When not logged in as an applicant it should be possible to apply for a job. Currently there is no button for that (see below)

![skarmavbild 2016-05-19 kl 13 14 00](https://cloud.githubusercontent.com/assets/16607246/15391878/100f2678-1dc4-11e6-8ec5-307b55432aed.png)

Expected outcome is that you should be redirected to a view where you get to choose between creating an account or logging in. Similar to the one below:

![skarmavbild 2016-05-19 kl 13 16 44](https://cloud.githubusercontent.com/assets/16607246/15391882/1432f694-1dc4-11e6-9704-e12723d3fb07.png)

**Comment by chris-sedp** [comment]
@FivelFred could you try to reproduce this one. I have seen the apply button disappear when changing windows size but i dont think thats the problem. This is some variable hanging in there from previous login or similiar.

**Comment by FivelFred** [comment]
I was logged in as a corporate user, I think that might be why I couldn't apply. And that is correct so I will close this one.
