### ISSUE TITLE
When a company is choosen, no information more than name and website is shown

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#426]
Should show the information available. 

![skarmavbild 2016-05-19 kl 13 29 18](https://cloud.githubusercontent.com/assets/16607246/15392166/bf338f1c-1dc5-11e6-9232-9cc8d458a5e9.png)

**Comment by chris-sedp** [comment]
@buren 
this resource retrieves all companies. Could you check if something is wrong there. What i need is a full company resource with street,zip and city.

**Comment by buren** [comment]
@chris-sedp looks like you're trying to retrieve one company? If so https://just-match-api-staging.herokuapp.com/api/v1/companies/43

**Comment by chris-sedp** [comment]
Of course @Buren :)..  Why are we even doing that call then. I will fix it.

However we need the full company data when using the single company resource or at least the data in the new company registration form that Fredric is referring to.

**Comment by buren** [comment]
@chris-sedp deployed an update. Additional company attributes are now returned.

**Comment by chris-sedp** [comment]
This one is working now. Closing
