### ISSUE TITLE
Possible to enter startdate in the future and end date that is in the past

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#427]
When creating a job it is possible to get to the next view with incorrect start and end date for the jobs. The input validation (error) comes first after you try to confirm the job you wish to post. 

So, this is possible to enter and click next;

![skarmavbild 2016-05-19 kl 13 08 24](https://cloud.githubusercontent.com/assets/16607246/15392445/6fbc44b8-1dc7-11e6-9d71-f30e31eb0402.png)

This happens first after you click confirm job in next step;

![skarmavbild 2016-05-19 kl 13 12 01](https://cloud.githubusercontent.com/assets/16607246/15392454/7b5ae540-1dc7-11e6-90d8-fa48f5da4296.png)

**Comment by ti-sedp** [comment]
Fixed
