### ISSUE TITLE
Unclear validation message for zip code on job creation

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#428]
Should be; The postcode should be in the following format or similar. 

![skarmavbild 2016-05-19 kl 13 04 58](https://cloud.githubusercontent.com/assets/16607246/15392500/bdedca8a-1dc7-11e6-9dae-1eb5bd6333ae.png)

Not to be done by launch due to long cycle times for translations!

**Comment by buren** [comment]
The api requires the zip to be exactly 5 characters, in other words spaces should be striped from the string.

**Comment by FivelFred** [comment]
Ok, so maybe this is a copy issue

**Comment by buren** [comment]
I think this actually should be handles a bit better/smarter on the apis side, i.e just strip out all spaces.

**Comment by FivelFred** [comment]
Will you sort this out @buren ?

**Comment by buren** [comment]
I'll update the api to be smarter about this. I'll also look into a plan for how to roll out a better validation error message.

**Comment by buren** [comment]
This has been fixed in the API.
