### ISSUE TITLE
Does not allow webbadress without http:// and does not explain the right format

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#429]
When entering a new job and the webpage it is not possible to click next without having http://. Should be possible without. 

![skarmavbild 2016-05-19 kl 13 05 21](https://cloud.githubusercontent.com/assets/16607246/15392560/11bc4f4c-1dc8-11e6-9cf1-f0f75860895e.png)

**Comment by buren** [comment]
The api returns as "nice" error message we should use that.

**Comment by ti-sedp** [comment]
I used standard angular input url may be we can add more ng-pattern but still don't have the perfect one actually it's work in both my chrome and firefox

**Comment by chris-sedp** [comment]
@ti the backend requires a full address and the angular url validation is ok. 

I have changed the validation text to explain the format needed
