### ISSUE TITLE
Telephone number is shown in black and not white as the other text in profile

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#430]
Should be white

![skarmavbild 2016-05-19 kl 13 51 47](https://cloud.githubusercontent.com/assets/16607246/15392662/eeb0173a-1dc8-11e6-9983-aaf7bf487b88.png)

**Comment by chris-sedp** [comment]
This is the autofill styles that is very hard to override. If filling your number again it will be in white.
