### ISSUE TITLE
No password reset email is being sent out when requested in interface

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#431]
Click log in
Click forgot password
Enter email
Click send
Nothing happens? 

Should send out an email with a new password. 

![skarmavbild 2016-05-19 kl 14 00 30](https://cloud.githubusercontent.com/assets/16607246/15392933/89c003ce-1dca-11e6-808f-c38382e163a4.png)

Is this blocked by API @buren

**Comment by FivelFred** [comment]
I still don´t recieve anything (on staging)

**Comment by buren** [comment]
The reason for this is that the worker on the server that sends emails have been disabled.. I've activated it again now..
