### ISSUE TITLE
Add frilans finans terms and conditions when choosing candidate and confirming interest

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#432]
Frilans Finans agreements should be accepted every time a job applicant accepting a job offer (see below). 

This is when it should be accepted as a private user; 
![skarmavbild 2016-05-19 kl 11 48 02](https://cloud.githubusercontent.com/assets/16607246/15393570/57060768-1dce-11e6-986e-35e368d8f3d8.png)

For the corporate user it is enough to accept Frilans Finans terms and conditions once, which is when they create an account (see below).

This is when Frilans Finans agreements should be accepted as a corporate user;
![skarmavbild 2016-05-19 kl 17 44 02](https://cloud.githubusercontent.com/assets/16607246/15399792/570a709e-1de9-11e6-9768-9bed20f24e0b.png)

In addition to having to be accepted @buren needs to find a way to log this agreement. 

@chris-sedp We might need you help with this on the front-end side of things.

**Comment by FivelFred** [comment]
According to Skype call with @buren and @chris-sedp this will be implemented on the above places. The agreement will be retrieved from the api. When a user accepts the agreement another signal must be sent to the api to confirm that it has been done and to provide some user info (for logging purpose). 

This will be implemented as two separate solutions, one for jobb applicant and one for jobb owner. Both with separate resources in the api.

**Comment by buren** [comment]
Implemented and documented at https://just-match-api-staging.herokuapp.com/api_docs/1.0/terms_agreements.html

**Comment by ti-sedp** [comment]
Fixed add checkbox for terms agreement and terms consent api

**Comment by chris-sedp** [comment]
Now its correct!
