### ISSUE TITLE
"New Jobs" and the list of "Show all" does not show the same jobs

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#433]
When posting a new job it does not come up on New Jobs on front page but it does on Show All. Should be the latest posted jobs that pop up on New Jobs. It happens both as logged in user and logged out user. 

How it looks on the starting page.
![skarmavbild 2016-05-19 kl 14 14 51](https://cloud.githubusercontent.com/assets/16607246/15393225/7a0f20a2-1dcc-11e6-8a3b-388c15856d1c.png)

How it looks on the Show all page (not the same)
![skarmavbild 2016-05-19 kl 14 14 59](https://cloud.githubusercontent.com/assets/16607246/15393229/7fcbd1ca-1dcc-11e6-8fa6-a3155922d876.png)

**Comment by Ubonrat** [comment]
Fixed.
