### ISSUE TITLE
Poor UX in changing bank account details as job applicant

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#435]
Log in as job applicant. Click on the wheel in the bottom of the meny. Click Bankuppgifter. Try to edit.

Have to click in the middle of the form to edit bank account details. Not possible to click on the text or just next to it as you might think. Should be possible. 

In addition, I can´t save. 

![skarmavbild 2016-05-19 kl 15 11 49](https://cloud.githubusercontent.com/assets/16607246/15394571/0cafb212-1dd4-11e6-8336-6363451bbce0.png)

**Comment by buren** [comment]
As I remember it we said that if you wanted to update your bank details you should contact support? This is not implemented in the api (currently).

**Comment by FivelFred** [comment]
You are right Jacob. For now; change Save to Contact support and link to contact form. 

Make the bank account details non-editable and remove password.

**Comment by buren** [comment]
Actually you update your account details.. using https://just-match-api-staging.herokuapp.com/api_docs/1.0/frilans_finans/create.html

**Comment by Ubonrat** [comment]
So changed Save to Contact support and link to contact form. Disabled the bank account form and removed password.
