### ISSUE TITLE
When clicking Register here! as logged in user - comes to edit profile

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#437]
When clicking on "Are you looking for part-time work" / Register here" as a logged in job applicant you come to your profile view. Should take you to the list of jobs if anything.  

When clicking here:
![skarmavbild 2016-05-19 kl 15 20 01](https://cloud.githubusercontent.com/assets/16607246/15394800/3003a2d6-1dd5-11e6-9d48-531622b07a8f.png)

I come to this:
![skarmavbild 2016-05-19 kl 15 18 06](https://cloud.githubusercontent.com/assets/16607246/15394809/37fcdf7a-1dd5-11e6-9f98-66f2b36ee97d.png)

Should take me here (if I am logged in and job applicant):
![skarmavbild 2016-05-19 kl 15 21 13](https://cloud.githubusercontent.com/assets/16607246/15394851/604bf7cc-1dd5-11e6-9bd1-fd751a7f75c6.png)

**Comment by Ubonrat** [comment]
Fixed.
