### ISSUE TITLE
Design and styling list to do

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#439]
- Interaktiviteten är ganska fattig i desktop, fler animationer vid hovering hade med fördel gett förbättrad UX (ex. nav.menyn och inputfält är bra dock!)
- De två boxarna under "Så kommer du igång" har inte samma höjd. Skär i ögonen på mig som detaljorienterad.
- Listan i den blå rutan på startsidan bör vara centrerad 
- Skapa mer luft mellan element, t.ex rubriken "En extra hand" och elementen som ligger under den

Stäng-Krysset i nav.meny ska vara ifyllt som de övriga
Namnet i inställningar delades upp på två rader istället för att hela namnet ligger på en rad
Knappen för att stänga kartan passar bättre uppe i högra hörnet
Uppdragen som man öppnar i kartan borde även gå att nå genom att klicka på deras rubrik (i pop-up-boxen)
Scrollar man upp i nav.menyn rör sig krysset

**Comment by pstenstrm** [comment]
Some things I cound't figure out how to fix:

* I can't find what "En extra hand" refers to

* I guess the name and last name fields needs to be separate. Moving them to the same line will leave the last name hanging and it doesn't really look very good. It might be easier if there were labels for the fields.

* I can't reproduce the close X movement on scroll

**Comment by lenaar** [comment]
1. There is no more "Extra hand section", you can skip it, I removed it and moved the blue steps for  section to carousel below

**Comment by buren** [comment]
A lot of this has been fixed over the last couple of months.
