### ISSUE TITLE
Implement promo code for app.justarrived.se

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#440]
@buren needs to provide parameter for @chris-sedp

**Comment by buren** [comment]
* URL parameter: `'?promo_code=`
* http://justarrived.dev-machine.com/#/user/signin should *not* require a promo code
* If not promo code is provided a page should be displayed with:
  - a link the login page
  - a link to justarrived.se stating that the app is still invite only

**Comment by chris-sedp** [comment]
@buren how do we know if the promo code is correct ?

**Comment by buren** [comment]
@chris-sedp 
https://just-match-api-staging.herokuapp.com/api_docs/1.0/promo_codes/validate.html
