### ISSUE TITLE
Remove respond.js lib

### ISSUE THREAD

**Issue by pstenstrm** [justarrived/just-match-frontend#462]
We are including the respond.js library on the site. Respond.js is a media query polyfill for browsers that don't support it. This mostly means IE8.

The site will not work in IE8 regardless since we're using Angular v1.5. Angular dropped IE8 support in v1.3. 

Can we remove respond.js or is it used in some other regard? And if so, can we rewrite those parts to not use respond.js?

**Comment by buren** [comment]
We can definitely remove the `respond` in `build.config.js` and `bower.json`, it was present in the start boilerplate that was used. 

https://github.com/justarrived/just-match-frontend/blob/ade0b1e76b8c206fe3a0e3880e9752ddf2493c08/build.config.js#L39

https://github.com/justarrived/just-match-frontend/blob/master/bower.json#L29

@pstenstrm you can open a PR for this if you'd like 👍 :)

**Comment by pstenstrm** [comment]
I think the same might be the case with underscore. The `build.config.js` includes both underscore.js and lodash.min.js. 

Lodash is loaded later so it will take over the `_` variable.

Can we remove underscore.js?
