### ISSUE TITLE
Accept terms & agreement label is not clickable

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#474]
If terms & agreement label is clicked it should check the checkbox. 

<img width="360" alt="screen shot 2016-05-22 at 14 49 31" src="https://cloud.githubusercontent.com/assets/922411/15454028/8d29808a-202c-11e6-8495-3f287d412a89.png">

**Comment by mblinovska** [comment]
Suggestion for copy improvement: I accept Just Arrived's **Terms & Conditions**.

**Comment by ti-sedp** [comment]
Fixed
add clickable label for checkbox
