### ISSUE TITLE
Create profile: UX fix - select image & copy improvement

### ISSUE THREAD

**Issue by mblinovska** [justarrived/just-match-frontend#476]
__Description__

UX - Profile pic: Select image + Copy improvement for Create Profile page. 

__Severity__: 
* Can perform without problem but looks wrong

__URL__: http://justarrived.dev-machine.com/#/user 

__Role__: User 

__How to recreate it__:

1. Go to Create profile (User profile)
2. Look at Profile picture. 

__What happend__: While creating a profile as a user I uploaded my profile pic, then when I wanted to fill in more details on my profile (Presentation, Language Skills, etc) I got an icon with a camera 'Select image' on the profile pic that I uploaded on the previous step. 

__Expected outcome__: Since I just uploaded my profile pic I don't see a point of changing it and even if so, I wouldn't expect to see a huge icon on my pic. It should be somewhere at the bottom/under the profile pic. 

_Screenshot_: 
<img width="1100" alt="screen shot 2016-05-22 at 15 15 49" src="https://cloud.githubusercontent.com/assets/18717885/15454152/19bdc9d6-2030-11e6-9aca-1b60fa7fe2d8.png">

_Copy improvement_: Create Profile - at the bottom of the page: Details **will be saved** to your profile and visible on all your **job applications**.

<img width="588" alt="screen shot 2016-05-22 at 15 19 29" src="https://cloud.githubusercontent.com/assets/18717885/15454172/9f2889e4-2030-11e6-971c-5e87ceacfb73.png">

__Browser (check what browser you're running at https://whatbrowser.org)__: Safari 9

**Comment by ti-sedp** [comment]
Fixed
