### ISSUE TITLE
Add user recordings script to app.justarrived.se

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#506]
justarrived.se

<script>
  (function(h,o,t,j,a,r){
      h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
      h._hjSettings={hjid:213564,hjsv:5};
      a=o.getElementsByTagName('head')[0];
      r=o.createElement('script');r.async=1;
      r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
      a.appendChild(r);
  })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>

app.justarrived.se

<script>
   (function(h,o,t,j,a,r){
       h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
       h._hjSettings={hjid:218430,hjsv:5};
       a=o.getElementsByTagName('head')[0];
       r=o.createElement('script');r.async=1;
       r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
       a.appendChild(r);
   })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by buren** [comment]
I'd say app.justarrived.se is the only domain we should add this for.

**Comment by buren** [comment]
What's the script @FivelFred? Or who has access to the account?

**Comment by FivelFred** [comment]
It is Antrops account and I´ve put the script as a comment.

**Comment by buren** [comment]
@FivelFred as a comment where? 😝

**Comment by FivelFred** [comment]
<script>
   (function(h,o,t,j,a,r){
       h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
       h._hjSettings={hjid:218430,hjsv:5};
       a=o.getElementsByTagName('head')[0];
       r=o.createElement('script');r.async=1;
       r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
       a.appendChild(r);
   })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by FivelFred** [comment]
Här är kodsnutten för www.appjustarrived.se. 

script
   (function(h,o,t,j,a,r){
       h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
       h._hjSettings={hjid:218430,hjsv:5};
       a=o.getElementsByTagName('head')[0];
       r=o.createElement('script');r.async=1;
       r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
       a.appendChild(r);
   })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
/script

**Comment by FivelFred** [comment]
Här är kodsnutten för www.appjustarrived.se. 

script
   (function(h,o,t,j,a,r){
       h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
       h._hjSettings={hjid:218430,hjsv:5};
       a=o.getElementsByTagName('head')[0];
       r=o.createElement('script');r.async=1;
       r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
       a.appendChild(r);
   })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
/script

**Comment by buren** [comment]
@FivelFred it should be `https://app.justarrived.se` not `http://www.appjustarrived.se`. Is that a typo? Or is that whats set in the Hotjar account? (If so we'll have to change it).

**Comment by FivelFred** [comment]
It is a typo but should not affect the Tracking Code as it is not in the script (only in the comment)?

**Comment by buren** [comment]
@FivelFred you're absolutely right :) The script is fine anyway, just thought we might need to look into the settings in Hotjar.

Can we ask Antrop to transfer ownership/add an admin account to a JustArrived email?

**Comment by FivelFred** [comment]
Yes, kollar med Camilla

**Comment by camillaryd** [comment]
Hi. Which justarrived email?

**Comment by camillaryd** [comment]
@buren @FivelFred

**Comment by buren** [comment]
@camillaryd `admin [at] justarrived.se`

**Comment by camillaryd** [comment]
@buren @FivelFred Hello. I've made a new hotjarproject for http://app.justarrived.se and here is the new script. Let me know when it's in place and I see if it works. You should also be able to reach it on hotjar with admin@justarrived.se


<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:229469,hjsv:5};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by buren** [comment]
@camillaryd awesome 👍 Thanks!

Ping @chris-sedp, @ti-sedp

**Comment by buren** [comment]
Hm... I'm a bit embarrassed that I haven't looked this up until just now.. but Hotjar actually doesn't have proper support for Single Page Applications (SPA) like ours is 😞
See their [docs](http://docs.hotjar.com/docs/does-hotjar-support-ajax--single-page-apps) and their [roadmap](http://docs.hotjar.com/v1.0/page/roadmap).

Despite this I think we can find a way of making Hotjar at least somewhat useful for us. Perhaps by manually sending/faking events or something along those lines. 

Hotjar would be an immensely useful product for us, so its worth some effort.

**Comment by buren** [comment]
Closing this, see comment: https://github.com/justarrived/just-match-frontend/issues/506#issuecomment-225373550

#745 replaces this issue for now.
