### ISSUE TITLE
At registration, copy should say personnummer/samordningsnummer 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#507]
![image](https://cloud.githubusercontent.com/assets/16607246/15603482/4b9d73d8-23fb-11e6-838a-1e1a565513d6.png)

**Comment by buren** [comment]
We should ask our users if they know what personnummer/samordningsnummer is and if they aren't really sure we're should also add a hint/description for the field.

**Comment by FivelFred** [comment]
Fixed
