### ISSUE TITLE
Chat does not work from time to time

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#513]
Nothing happens when you press send. Tried in staging.

**Comment by ti-sedp** [comment]
Which user and job id that the bug happen?

**Comment by ti-sedp** [comment]
I add more condition before send Chat message api. Let's see. It still happen or not.

**Comment by FivelFred** [comment]
I will make sure to document this thoroughly next time. It has happen to me three times by now.

**Comment by ti-sedp** [comment]
I re-structure code in company job chat. I tested it before pull request. Let's try it in company job chat page
