### ISSUE TITLE
Image cropping does not work in round format 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#514]
![image](https://cloud.githubusercontent.com/assets/16607246/15604207/6469c3fe-23ff-11e6-9542-a644feccc1f4.png)

Does not center and scale a square photo in round format as in front-end.

**Comment by ti-sedp** [comment]
My logo show correct center and cover
Can you send the image url to me?

![2559-05-27_16h44_23](https://cloud.githubusercontent.com/assets/16758634/15604385/4a449f00-242a-11e6-8c6e-a597a4c21887.png)

**Comment by FivelFred** [comment]
http://just-match-frontend-staging.herokuapp.com/#/arriver/jobs

username: fredric+22@justarrived.se
password: password

**Comment by ti-sedp** [comment]
Because of your image have a thick white border around it so it's look like the image not scale

![2559-05-27_21h08_52](https://cloud.githubusercontent.com/assets/16758634/15610416/52d5ad24-244f-11e6-9fe5-27d969e9924d.png)
