### ISSUE TITLE
IBAN and BIC should be optional and require action to be availible 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#517]
Currently the user can enter Bank name, account number, IBAN and BIC.

Bank name, clearing number and account number should be standard fields. Below these there should be a text saying; "Don´t have a Swedish bank account? Click **here** to enter BIC and IBAN." That should trigger that BIC and IBAN appear below. 

![image](https://cloud.githubusercontent.com/assets/16607246/15606185/d306b58c-240a-11e6-9778-71af85ef3ad0.png)

**Comment by ti-sedp** [comment]
Fixed

- add new translate word code "assignment.enable_bic_iban.description" need to translate 
"Har du inte ett Svenskt bankkonto? Klicka här för att ange BIC eller IBAN"
"Don´t have a Swedish bank account? Click here to enter BIC and IBAN."
