### ISSUE TITLE
Hardcoded remaining time in ArriverJobCtrl

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#525]
The API returns a field `will-perform-confirmation-by`, that can be used to calculate the time remaining. This way the rules for time remaining can be configured in the API, without changing the frontend.

See

* https://github.com/justarrived/just-match-frontend/blob/master/src/app/common/controllers/ArriverJobCtrl.js#L158-L176
* https://github.com/justarrived/just-match-frontend/blob/master/src/app/common/controllers/ArriverJobCtrl.js#L104

**Comment by ti-sedp** [comment]
Fixed
