### ISSUE TITLE
Hardcoded text string in CompanyJobCtrl

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#527]
See

* https://github.com/justarrived/just-match-frontend/blob/master/src/app/common/controllers/CompanyJobCtrl.js#L25
* https://github.com/justarrived/just-match-frontend/blob/master/src/app/common/controllers/CompanyJobCtrl.js#L201
* https://github.com/justarrived/just-match-frontend/blob/master/src/app/common/controllers/CompanyJobCtrl.js#L460
* https://github.com/justarrived/just-match-frontend/blob/master/src/app/common/controllers/CompanyJobCtrl.js#L673

**Comment by ti-sedp** [comment]
Fixed
