### ISSUE TITLE
Google map zoom level 

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#531]
Currently even if all jobs are placed closed to each other the map is really zoomed out (see screenshot), we should calculate the appropriate zoom level.. 

## Screenshot 

![screenshot_20160604-214208](https://cloud.githubusercontent.com/assets/922411/15801699/a835cd0e-2a9d-11e6-8cf9-9c044f7e5084.png)

**Comment by ti-sedp** [comment]
Fixed
