### ISSUE TITLE
Profile image and company logo is removed if validation error occurs 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#534]
When registering a profile or job and you upload an image it disappears if you get validation error. 

How to recreate:

1) Create job or profile
2) Make a faulty entry 
3) Upload image
4) Click next

Should keep the image.

**Comment by chris-sedp** [comment]
I think this is normal form behaviour. Password fields and file fields usually looses their content. Lets see what we can do about it.

**Comment by ti-sedp** [comment]
Fixed
