### ISSUE TITLE
Text informing the user about google translate and to not use "slang"

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#542]
In all user generated text fields like profile, job description, comment and chat it should state that google translate is used to do the translation. In this example it should be added with the recommendation to fill out all forms. 

![skarmavbild 2016-06-10 kl 14 09 14](https://cloud.githubusercontent.com/assets/16607246/15963865/751cca9a-2f15-11e6-9f7c-6a0dcb6912b4.png)

**Comment by chris-sedp** [comment]
@FivelFred Do you have copy for this and I will put it in.

**Comment by FivelFred** [comment]
I will provide you with this soon, I'll get back during the afternoon.
