### ISSUE TITLE
After completing a profile the user should choose to find job or preview profile

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#543]
After finishing profile you should be able to preview profile. The most straight forward way is by simply having a button under "Find Jobs" which states "View Profile".

![skarmavbild 2016-06-10 kl 13 59 27](https://cloud.githubusercontent.com/assets/16607246/15963900/af84c552-2f15-11e6-82f2-6bc7476b137f.png)

**Comment by ti-sedp** [comment]
Fixed

**Comment by FivelFred** [comment]
Perfect
