### ISSUE TITLE
When refreshing a certain views the texts are not retreived

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#544]
When refreshing the view for confirmation  on creating a profile no texts are retrieved. Should show the text and not text-code-strings.
 
![skarmavbild 2016-06-10 kl 14 00 00](https://cloud.githubusercontent.com/assets/16607246/15964053/d226d5f4-2f16-11e6-9b66-df7003188dba.png)

**Comment by ti-sedp** [comment]
Fixed
