### ISSUE TITLE
In comments it should be visible if you represent the company posting the job

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#547]
As in chat, it should state that you are representing a company when you post a comment as a job owner. Like this:

![skarmavbild 2016-06-10 kl 14 35 11](https://cloud.githubusercontent.com/assets/16607246/15964517/31c1e696-2f19-11e6-8ba4-959a0aea0dd4.png)

Currently there is no way of knowing. You can´t see the differance between a corporate user and a private user. See below: 

![skarmavbild 2016-06-10 kl 14 37 10](https://cloud.githubusercontent.com/assets/16607246/15964526/3d4c2abc-2f19-11e6-968f-fc2fc252ef87.png)
![skarmavbild 2016-06-10 kl 14 34 34](https://cloud.githubusercontent.com/assets/16607246/15964527/3d508576-2f19-11e6-93cd-fc86c9ccd13c.png)

**Comment by ti-sedp** [comment]
Fixed
