### ISSUE TITLE
In profile, a star is displayed randomly in pink although the user does not have a rating

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#548]
Should not be a star there if they do not have a rating. Or state "N/A" (Not applicable) next to the star. 

![skarmavbild 2016-06-10 kl 14 44 34](https://cloud.githubusercontent.com/assets/16607246/15964672/f4136198-2f19-11e6-9ea5-e19e7cec0c75.png)

**Comment by ti-sedp** [comment]
Fixed
hide start if user don't have rating
