### ISSUE TITLE
Chat box for comment and chat should expand down

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#549]
When writing long messages in chat and comment they move the text from left to right. Should expand the textbox downwards if the message becomes long. 

![skarmavbild 2016-06-10 kl 14 48 16](https://cloud.githubusercontent.com/assets/16607246/15964763/6faaa2ee-2f1a-11e6-9400-1527717699d6.png)

**Comment by FivelFred** [comment]
And the chat input function (where you write the message before sending) should be sticky in bottom of page so it is always visible for the user.

**Comment by ti-sedp** [comment]
Fixed
- Expandable comment textbox in Job view
- Expandable+Sticky comment textbox in Job Arriver
- Expandable+Sticky comment textbox in Job Company
- Expandable+Sticky chat textbox in Job Arriver
- Expandable+Sticky chat textbox in Job Company
