### ISSUE TITLE
New message in chat and in comments should come at the buttom of conversation not top

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#550]
The messages are added from the top but should be from the buttom like every other application in the world.

![skarmavbild 2016-06-10 kl 14 37 10](https://cloud.githubusercontent.com/assets/16607246/15965085/1eb31248-2f1c-11e6-85b4-6a6c85863b83.png)

**Comment by buren** [comment]
The only drawback of this would be if the conversation gets long.. Perhaps we should add some box around the chat that will scroll after the content has reach is max height.

**Comment by ti-sedp** [comment]
Fixed

**Comment by FivelFred** [comment]
Thanks. @ti-sedp, Is it possible to make the "new message part" sticky at the bottom of the page?
