### ISSUE TITLE
New arrival should get the opportunity to rate the company

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#551]
As the company rates the new arrival...

**Comment by buren** [comment]
(FYI: Already supported in the API, so its just a matter of adding it to the UI)

**Comment by chris-sedp** [comment]
@FivelFred Where exactly in the flow should this be set ?

**Comment by ti-sedp** [comment]
![2559-06-13_17h29_06](https://cloud.githubusercontent.com/assets/16758634/16004591/a0324b78-318c-11e6-8674-7aaffe4ae22f.png)

Is this this a good place to put the raitings ?
when click Ja button show the rating form

**Comment by FivelFred** [comment]
Yes, after the job performer has accepted the completion of a job they should get the chance to rate the company (a rating not publicly displayed but for us to have as reassurance of quality of jobs)

**Comment by ti-sedp** [comment]
After I set user performed a job, I try to set rating and api return error like this. Did i call api wrong step? @buren 

![2559-06-20_14h55_58](https://cloud.githubusercontent.com/assets/16758634/16186879/520f4db8-36f7-11e6-87c8-68ad345b67bc.png)

**Comment by buren** [comment]
@ti-sedp an invoice must be created first, otherwise the job is not considered concluded/finished.

**Comment by ti-sedp** [comment]
Fixed
it's in arriver jobs list - arkiv tab
![2559-06-21_15h51_18](https://cloud.githubusercontent.com/assets/16758634/16223559/1dab2336-37c8-11e6-8738-29304a3990d9.png)
![2559-06-21_15h51_26](https://cloud.githubusercontent.com/assets/16758634/16223565/217ca552-37c8-11e6-8709-7d36f93e1f49.png)

**Comment by FivelFred** [comment]
Sorry for not being specific on this issue. What I intended was that the option to rate should come up directly after the user has approved that the job is performed. I have done a sketch (attached) how I would like it to look:

![how review should work for job perfomer](https://cloud.githubusercontent.com/assets/16607246/16262271/2f3402e2-386f-11e6-9afb-d9dfc7e3d205.png)

**Comment by FivelFred** [comment]
You can add new text references for me to draft later. They will differ slightly from the ones for the corporate user.

**Comment by ti-sedp** [comment]
as @buren told. 
invoice must be created first, otherwise the job is not considered concluded/finished.

**Comment by FivelFred** [comment]
@buren can we support front-end to improve this user flow?

**Comment by buren** [comment]
@FivelFred sure I can update the validation rules for this.

**Comment by buren** [comment]
See https://github.com/justarrived/just_match_api/issues/453

**Comment by ti-sedp** [comment]
Fixed
new word code
"user.assignment.rating.submit.description"
"assignment.status.salary_will_be_paid"
"assignment.status.performed"
