### ISSUE TITLE
Should be possible to enter organisation number with hyphen (-) 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#559]
The application should allow both or adjust the organisation number by removing the hyphen in the front-end

![Uploading unnamed.png…]()

**Comment by chris-sedp** [comment]
@buren Will this validate in the api or should we allow it and strip the hyphens before posting the data. ? 

This mean that the orgnumber will show without hyphens after submit

**Comment by FivelFred** [comment]
We need to fix this asap and push to production. All companies get stuck on this. @chris-sedp can you look into this? 
Fredric 
Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Christopher <notifications@github.com> 
Datum: 06-13-2016  12:21  (GMT+01:00) 
Till: justarrived/just-match-frontend <just-match-frontend@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Author <author@noreply.github.com> 
Rubrik: Re: [justarrived/just-match-frontend] Should be possible to enter
  organisation number with hyphen (-)  (#559) 

@buren Will this validate in the api or should we allow it and strip the hyphens before posting the data. ? 

This mean that the orgnumber will show without hyphens after submit

**Comment by ti-sedp** [comment]
Fixed 
allow 0-9 and - "/^[\d\-]+$/". 
remove hyphen before send it to api server

**Comment by FivelFred** [comment]
Great. Please push this change to production. Thanks.
