### ISSUE TITLE
User "settings view" bugs

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#560]
There are a few things wrong with the current implementation of the users settings view (the view that you're taken to when clicking the gear-icon). 

1. When saving the form a request is made to `/users/sessions`, why is that? (some security measure?)
2. You can't update the password (no requests is ever made to `/users/change-password`
3. An error is thrown when saving the form (see screenshot below).

![skarmavbild 2016-06-13 kl 11 10 44](https://cloud.githubusercontent.com/assets/922411/16017010/39ca37a8-319e-11e6-87e0-b2452dafbf20.png)

**Comment by ti-sedp** [comment]
![2559-06-17_12h42_10](https://cloud.githubusercontent.com/assets/16758634/16141737/eee2e76a-3488-11e6-8e24-76cbf6237707.png)

In setting view we can change password by input old password and new password
if user change password i'll check old password is correct by try login email and old-password by api
if old-password correct, I'll continue after that i'll try login again with new-password

**Comment by FivelFred** [comment]
@ti-sedp does it work to reset the password in the interface buren posted?

**Comment by Belev** [comment]
Everything seems to work as expected. Closing the issue.
