### ISSUE TITLE
Validation for organisation number is incorrect

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#565]
Currently it says: Enter organisation number as YYMMDDXXXX (see below)

![skarmavbild 2016-06-14 kl 12 31 41](https://cloud.githubusercontent.com/assets/16607246/16039785/2ee12714-322c-11e6-9c93-5412add1bc7b.png)

When it should say: Enter the ten digit organization number as XXXXXXXXXX (without hyphen)

**Comment by ti-sedp** [comment]
Change YYMMDDXXXX to XXXXXXXXXX
