### ISSUE TITLE
"Jobbkategori" should be availible in english as well

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#570]
Today you can only enter the job category in swedish, should be possible in english as well.

**Comment by buren** [comment]
The reason for this is that Frilans Finans only provides the category names in Swedish. What makes this a bit tricky to fix is that there are ~8200 job categories so it is _a lot_ of strings to translate. Not sure how we should go about fixing this.

**Comment by buren** [comment]
We wont be able to do this, due to the reasons stated in https://github.com/justarrived/just-match-frontend/issues/570#issuecomment-226548963.

We should however look into having a separate category that we control 💯%
