### ISSUE TITLE
Seems like the plattform retrieves source language and then translates

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#572]
When the user has slow connection the platform renders first the source language and the later the chosen locale.

**Comment by buren** [comment]
@FivelFred could you perhaps provide an example?

Do you mean that the loading of strings translated in the frontend is first displayed in the default language (English) and then when _something_ has been loaded the users current locale is loaded and then the page is displayed in the correct language?

(For strings translated with Google Translate its not much we can do, but wait for the Google Translate API.)

**Comment by FivelFred** [comment]
Yes, that was what I meant. Ok, if we can not make it faster with Google Translate so be it.
