### ISSUE TITLE
Can not click job on enitre section, need to click amount or image

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#573]
When looking into the job section the user needs to click the amount, name or company image to be able to preview the job. Should be possible to click the entire "work card" i.e. the white section on which the information is displayed. 

![skarmavbild 2016-06-14 kl 16 49 23](https://cloud.githubusercontent.com/assets/16607246/16072418/10caecc8-32e1-11e6-8e80-bc2df07024f5.png)

**Comment by ti-sedp** [comment]
Fixed
