### ISSUE TITLE
'Apply for job' button should be default (to not render the other button when having slow connection)

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#574]
Currently, if the user has a slow connection the 'You have applied for the job' button/indicator is rendered first and then the 'Apply for job' comes up. Would be better to have 'Apply for job' as default and then loading the other one if applicable. Simple to replicate but hard to communicate in photo so let me know if you need additional input on this one.

**Comment by ti-sedp** [comment]
Hide apply and applied button first
