### ISSUE TITLE
When clicking on a job under `Other jobs' you don´t get to the top of the page in that job

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#575]

**Comment by pstenstrm** [comment]
I thought I had a pretty easy solution to this issue. Simply enabling autoscroll: `<div class="container-fluid" ng-view autoscroll></div>`. It does however also force the browser window to top when the user is navigating through history back, which isn't preferable I think.

It might still be a better solution than the current state though.

**Comment by buren** [comment]
@pstenstrm I'm 👍 for merging your fix 97f4119. At least, in my point of view, this thats better than what we have now.

Created a PR for this #744.
