### ISSUE TITLE
Should be possible to get jobs translated at starting page 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#578]

**Comment by FivelFred** [comment]
![skarmavbild 2016-06-14 kl 16 46 38](https://cloud.githubusercontent.com/assets/16607246/16047259/b3d2cebe-324f-11e6-9b50-3d9d8c4eaab2.png)

**Comment by FivelFred** [comment]
Same thing as under the full job list there should be an option to translate the job titles on the landing page. Would you be able to look into this @chris-sedp ?

**Comment by ti-sedp** [comment]
Fixed
