### ISSUE TITLE
Show all jobs view removes capital letters on the jobs

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#579]
![skarmavbild 2016-06-14 kl 16 49 23](https://cloud.githubusercontent.com/assets/16607246/16047351/069bb2fa-3250-11e6-8642-8732006fb873.png)

![skarmavbild 2016-06-14 kl 16 50 10](https://cloud.githubusercontent.com/assets/16607246/16047377/1b3fc34a-3250-11e6-8db3-200f6d65cea5.png)

**Comment by ti-sedp** [comment]
Look like street attribute not return from api. It'll auto bind data after api fixed

https://just-match-api-staging.herokuapp.com/api_docs/1.0/jobs/index.html
https://just-match-api-staging.herokuapp.com/api_docs/1.0/jobs/show.html

![2559-06-16_13h46_11](https://cloud.githubusercontent.com/assets/16758634/16107774/c1c6c8fc-33c8-11e6-95be-eca7fa1c6eb5.png)

**Comment by ti-sedp** [comment]
Sorry i misunderstand it

**Comment by ti-sedp** [comment]
Fixed
Remove text-transform capitalize
