### ISSUE TITLE
When refreshing issue it takes you to profile when it should be updating chat

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#582]
Should be one separate URL for each submeny under the profile of the candidate you wish to choose. So Profile should have one, Chat one and reviews one. That way if you update the chat to see new messages it should not take you to profile every time. 

~~In the long term it would be better if the chat automatically updated itself every 30 seconds for five minutes after you have written something.~~ See #603

**Comment by FivelFred** [comment]
This needs to be fixed ASAP. Currently we send out an email to job applicants and job owners when they get a new message. That message contains a link (https://app.justarrived.se/#/chat/ID) where ID is dynamic. We therefore to set up an url for the chat which is https://app.justarrived.se/#/chat.

**Comment by ti-sedp** [comment]
Fixed add chat route

For Coporate User
![2559-06-22_14h48_20](https://cloud.githubusercontent.com/assets/16758634/16258597/c3533380-3888-11e6-8396-31ff89557e42.png)


For Arriver User
![2559-06-22_14h50_08](https://cloud.githubusercontent.com/assets/16758634/16258610/d0ae4c0e-3888-11e6-9a04-47b81d8ecc06.png)

**Comment by FivelFred** [comment]
Great! Thanks Ti. Can you push to staging so I can try it out?
