### ISSUE TITLE
Put's in weird text when writing '  

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#584]
![skarmavbild 2016-06-14 kl 17 09 35](https://cloud.githubusercontent.com/assets/16607246/16048047/db5803e8-3252-11e6-9f1f-3b70f46eec55.png)

**Comment by ti-sedp** [comment]
Fixed
![2559-06-16_11h57_45](https://cloud.githubusercontent.com/assets/16758634/16105914/9be1e518-33b9-11e6-9bb4-fdf527598bd6.png)
