### ISSUE TITLE
In comments the user can´t see the next action like in chat - should be able 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#585]
![skarmavbild 2016-06-14 kl 17 25 13](https://cloud.githubusercontent.com/assets/16607246/16048642/249694f0-3255-11e6-9b28-f327b429c606.png)

![skarmavbild 2016-06-14 kl 17 25 21](https://cloud.githubusercontent.com/assets/16607246/16048643/24b29286-3255-11e6-8009-206e39859dab.png)

**Comment by buren** [comment]
I'm not sure what you mean by this @FivelFred could you perhaps elaborate :)

**Comment by buren** [comment]
💤
