### ISSUE TITLE
Hard to go between the comments page and the chat page

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#586]

**Comment by buren** [comment]
Assigning you @FivelFred so you can update the issue with enough information to implement something :)

**Comment by buren** [comment]
💤

**Comment by pstenstrm** [comment]
I think this was an issue related to that the comments page and chat page didn't have unique urls, and not navigation actions on the page to go back from comment/chat and the job page.

So the only way around was back to whatever route you visited before the job page or somewhere else entirely in the app
