### ISSUE TITLE
User can not see job description, adress or sum of job once in My jobs

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#587]
My suggestion is that the top field of a job in 'My jobs'  can be expanded downwards by pressing a symbol (arrow). Should then display all information like description and phone number to the person. 

This is a sketch of how it could look:

![see more info](https://cloud.githubusercontent.com/assets/16607246/16297714/4a7b96aa-3932-11e6-912e-eed2668388d6.png)

Would not mind having Camilla Ryds input here....

**Comment by ti-sedp** [comment]
Fixed show job detail 
For gross-salary and net-salary show the same as job detail page
