### ISSUE TITLE
Validating company street field

### ISSUE THREAD

**Issue by pstenstrm** [justarrived/just-match-frontend#604]
__Description__

When registering a new company the street address field does not get validated when the user leaves  the field. The user can continue to fill the form and click the "Continue"-button. If there is a validation error it will be shown but the user can no longer edit the form and are stuck.

__Severity__:

* Can perform with problem

__URL__: http://justarrived.dev-machine.com/#/company/register

__Role__: Not logged in

__How to recreate it__

1. Goto http://justarrived.dev-machine.com/#
2. Click the menu icon -> Create account -> Companies
3. Enter a new company identification number
4. Enter a value of les than 5 characters in the street field
5. Fill the rest of the form 
6. Click Continue

__What happend__
The company form is disabled and there's a validation error on the street field

__Expected outcome__
The street field should validate when the field loses focus

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome v50

__Screenshot__

<img width="588" alt="screen shot 2016-06-16 at 19 11 18" src="https://cloud.githubusercontent.com/assets/1674417/16126277/b81708ce-33f7-11e6-9ce7-07f9ac04e3cf.png">

**Comment by buren** [comment]
Currently the API doesn't expose the validation rules, they're only documented in the API documentation. This means that the frontend needs to duplicate all of those rules, so if the API validations is updated the frontend need to be updated too.

I've thought a bit about how this could be done and I'm not sure what the best approach would be, but so far I see these options:

1. Expose the validations rules `GET /companies/validations`
2. Develop a stand-alone JavaScript API client (thinking of doing this anyway) that would be fetched from `api.justarrived.se/v1/client.js` that would be controlled and, partially, generated by the API
3. Leave it as is and duplicate the validations rules between the frontend and API

Any input would be greatly appreciated.

**Comment by pstenstrm** [comment]
I think a start is to never disable the form if it's a new company registration. I'll add my comments to the gist

**Comment by FivelFred** [comment]
Well spotted bug Per! Keep up the good work :)

**Comment by ti-sedp** [comment]
Fixed
