### ISSUE TITLE
Display both gross salary and net salary 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#619]
Before it looked like this: 

![skarmavbild 2016-06-20 kl 11 53 53](https://cloud.githubusercontent.com/assets/16607246/16190393/53728a3e-36df-11e6-9d73-63827df3062a.png)

I would like to showcase both gross and net salary like this:

![skarmavbild 2016-06-20 kl 12 05 16](https://cloud.githubusercontent.com/assets/16607246/16190396/61e1611c-36df-11e6-9de5-af404fe7eb12.png)

Both will be provided by the API. I will update this issue on how it should look in other places in the application. Where it says *api* it should retrieve the number from the api.

**Comment by ti-sedp** [comment]
when we come with coporate user 
- 862 SEK calculate from (rate-excluding-vat * hour)
- (108 SEK / hour) 108 is gross-salary
- *API* SEK calculate from (net-salary * hour)

when we come with arriver user
- 862 SEK calculate from (gross-salary * hour)
- (108 SEK / hour) 108 is gross-salary
- *API* SEK calculate from (net-salary * hour)

Am i understand correctly?
@FivelFred

**Comment by ti-sedp** [comment]
Fixed
