### ISSUE TITLE
Time remaining displayed twice when accepting job as applicant

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#620]
When accepting a job, time remaining is displayed twice. Both in the pink section and in the confirm job section. Should only be in the pink section. See image below of how it looks now: 

![time remaing x2](https://cloud.githubusercontent.com/assets/16607246/16196405/10388bbe-36fe-11e6-8fca-2dd81449956c.png)

**Comment by FivelFred** [comment]
![time remaing x2](https://cloud.githubusercontent.com/assets/16607246/16196380/fa026126-36fd-11e6-8043-27f8d2a870c0.png)

**Comment by buren** [comment]
Also please calculate the time remaining by using the datetime returned by the API (`job-users/`).

**Comment by ti-sedp** [comment]
Fixed
Yep remaining time calculate from will_perform_confirmation_by and current time

**Comment by FivelFred** [comment]
Great @ti-sedp
