### ISSUE TITLE
Text string not loaded - only reference visible 

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#641]
When posting a job there is text reference that does not generate a text string. I think it is because the string is written as: *assignment.create.description* but the actual text reference in the JSON file is  assignment.create**d**.description

![text code without string](https://cloud.githubusercontent.com/assets/16607246/16229080/2887ba24-37bb-11e6-9f82-667c76a3b275.PNG)

**Comment by ti-sedp** [comment]
Fixed
