### ISSUE TITLE
Should be possible to log-in with phone number AND e-mail as "user name"

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#651]
We want to make it possible to log in to the application by either phone number or email, depending on what the user prefers. This is supported in the API why it should not be complicated to implement. Instead of user name (as in picture below) it  should say Phone number or Email (this is something I can fix, as long as you ping me when phone number as login is implemented).

**Comment by buren** [comment]
tl;dr You can now send a parameter `email_or_phone` to the API.

See the updated docs: https://api.justarrived.se/api_docs/1.0/user_sessions/create.html

**Comment by ti-sedp** [comment]
Fixed
