### ISSUE TITLE
Same text references comes back in two views but are unrelated

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#652]
When creating an assignment as corporate user you are exposed to the same text twice (see below).

![double2](https://cloud.githubusercontent.com/assets/16607246/16257974/e0acc4e6-385b-11e6-894e-8e9712d5d6a0.PNG)
![double](https://cloud.githubusercontent.com/assets/16607246/16257975/e0b1414c-385b-11e6-9cc3-d5d71ff8c936.PNG)

The first text, i.e. the one when filling in the input fields should be a different one. Please provide a new text reference and I can draft a text.

**Comment by ti-sedp** [comment]
OK this one "assignment.create.description"
