### ISSUE TITLE
Uploading image text is in Swedish, regardless of locale

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#656]
"Välj" (choose) and "Ingen fil har valts" (no file has been selected) are fixed regardless of which language the user choose (see below). 

![hard coded swedish](https://cloud.githubusercontent.com/assets/16607246/16259228/e49dadda-3861-11e6-81e6-74c87f6276fd.PNG)

Should be translated to the users locale and have text references to JSON file for translation.

**Comment by pstenstrm** [comment]
This is based on the language chosen on the users operating system and nothing we can really change. 

If the user visits the site on an iPhone with iOS language set to arabic the button will be in arabic.

What we can do is to design our own "Choose file" button and have a transparent file picker positioned above it. But it might not be that urgent.

**Comment by FivelFred** [comment]
Thanks for good input @pstenstrm. Lets park this one for now.

**Comment by buren** [comment]
That text is actually decided by the browser and is always rendered with in the language that you have the browser in. 

There are ways around it, but it's not a string that is hard coded in the app..

**Comment by buren** [comment]
Replaced this issue with ☝️
