### ISSUE TITLE
Not possible to update profile due to mobile phone error

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#669]
When I try to update my password I get the error code that the mobile phone number already exists. I have however not edited the phone number. Maybe front-end should only try to update input fields that are edited? 

![skarmavbild 2016-06-28 kl 09 22 38](https://cloud.githubusercontent.com/assets/16607246/16407077/0d9ee866-3d12-11e6-8aa8-09f7b1ff752e.png)

**Comment by FivelFred** [comment]
@buren any input on how to do this issue?

**Comment by FivelFred** [comment]
@buren can you ensure that this is not blocked by API?

**Comment by buren** [comment]
Well this is, and should, be blocked by the API. As the validation error states the number is not unique and therefore should not be accepted. Users now can log in using their phone number and therefore it must be unique. 

@FivelFred we should update your phone number, alternatively just remove that user from the system.

**Comment by buren** [comment]
@FivelFred created an issue for this in (see ☝️), so we can track and make sure this is done.
