### ISSUE TITLE
Information missing under candidate's profile

### ISSUE THREAD

**Issue by camillaryd** [justarrived/just-match-frontend#683]
__Description__

All information under profile is missing, when a company user review a candidate who applied for a job, 

__Severity__:

* Can not perform action

__URL__: https://just-match-frontend-staging.herokuapp.com/#/company/job/251/candidate/490

__Role__: Company user /  

__How to recreate it__

1. Goto my jobs.
2. Click on a job
3. Review applicants
4. Go to one applicants profile
5. Go to the toggle "profile"

__What happend__

We created a user and a profile to apply for a job. 
Then we logged in as a company user to review the applicant and there is no information displayed on the applicants profile. 

__Expected outcome__

Expected it to display the information 

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

![image](https://cloud.githubusercontent.com/assets/19821275/16731573/3353afda-4779-11e6-805a-be7df5cb0f25.png)

**Comment by buren** [comment]
Actually this is because that user hasn't filled out any of those fields..

Maybe we should indicate that more clearly by adding a "Not given" or something like that to fields that aren't filled out. Or what do you think @camillaryd?

**Comment by camillaryd** [comment]
@buren But we went through the flow for that specific user and filled in the information. Weird.

**Comment by buren** [comment]
@camillaryd hm.. ok that worries me quite a bit. Perhaps there is another bug which causes those fields not to be sent to the backend. I'll definitely look into it more!

**Comment by buren** [comment]
## Investigate

There might be a bug in the frontend that causes some fields not to be sent to the backend/API, the fields that needs to be double checked are:

* `education`
* `job_experience`
* `description`
* `competence_text`
