### ISSUE TITLE
The pink colour looks toxic on some screens

### ISSUE THREAD

**Issue by camillaryd** [justarrived/just-match-frontend#684]
__Description__

The Primary Colour, the JA PINK look toxic on some screens, to the point where it scratches your eyes and you loose contrast. Is it the right Hex: #E5007D? Otherwise, we need to make it less saturated.

**Comment by buren** [comment]
@camillaryd at first glance it looks like that the pink colour used across the application. 

Here is a list of all the colours used in the application:

```sass
$white: #FFFFFF;
$dark: #121315;
$darkBlue: #222531;
$lightBlue: #383F4E;
$lightHalfBlue: #9b9fa6;
$grey: #979797;
$midgrey: #c8cdd2;
$lightGrey: #E8EBEE;
$blue: #0069d2;
$brightBlue: #00D7FF;
$darkGrey: #2A303D;
$pink: #E5007D;
$spacing: 10px;

// Buttons
$btnBgColorPositive: #e5007d; //dark hot pink
$btnTxtColorPositive: #fff;
$btnBgColorNegative: #383f4e; //charcoal grey
$btnTxtColorNegative: #fff;
$btnTxtColorDisabled: #eee;
$btnOpacityDisabled: 0.5;
$btnBorderRadius: 24px;

// Hover states
$lightBlueHover: darken($lightBlue, 10%);
$greyHover: darken($grey, 10%);
$pinkHover: darken($pink, 5%);

$btnBgColorPositiveHover: darken($btnBgColorPositive, 5%);
$btnBgColorNegativeHover: darken($btnBgColorNegative, 5%);

$transparentHover: rgba(0,0,0,.2);
```

**Comment by camillaryd** [comment]
Okay. Then we need to take make it less saturated, I'll look into it.

**Comment by camillaryd** [comment]
Hello there. I've updated the style guide on Zeplin.io, with two more values of the cerise which are darker than the logo cerise, #E5007D. They have better contrast with white text and it is nice to have more values of the same hue in the interface. View the color palette here: https://zpl.io/Zgfw2d

- All cerise buttons should be updated with #C3106C according to the manual on zeplin.io https://zpl.io/R7gaW
- The backgrounds on the CTA on the landing page should be updated to #31066C and #971057 as you can see in the mock-up here: https://zpl.io/Z1IJ0kt

**Comment by pstenstrm** [comment]
I can update the style. Can you add me to zeplin?

**Comment by camillaryd** [comment]
@pstenstrm yes. to what email/username on Zeplin?

**Comment by pstenstrm** [comment]
Same username as here, thanks.

**Comment by buren** [comment]
Thank you @camillaryd and @pstenstrm 🎈
