### ISSUE TITLE
As a not logged in user, I want to be able to see available jobs in the start page

### ISSUE THREAD

**Issue by camillaryd** [justarrived/just-match-frontend#685]
__Description__

You do not se the thumbnails for the jobs on the landing page if you're not signed in. Since this is one way to on board both targets groups it's a must have to view the on the landing page even if you haven't logged in yet. 

__Severity__:

_Chose one of the below:_

* Can perform without problem but looks wrong

Not logged in

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome

__Screenshot__

![image](https://cloud.githubusercontent.com/assets/19821275/16781359/2a974494-487b-11e6-82ed-d965eebc270d.png)

**Comment by pstenstrm** [comment]
I think that is how it works already, but it take a very long time to load initially.

**Comment by buren** [comment]
The reason for this is that we're using Herokus (our hosting providers) free tier. What that means is that if no requests are made in a few minutes the server will go to "idle mode" and the next request would first have to "wake up"/boot the server and then serve the requests. That takes ~10-15sec.. so this is not an issue in production.
