### ISSUE TITLE
If I don't know what specialist I'm looking for, I want to be able to select an open category

### ISSUE THREAD

**Issue by camillaryd** [justarrived/just-match-frontend#691]
__Description__

The categories from Frilans Finans are based on specialities, but if I'm looking for is "unqualified", can we have a category for this?

**Comment by buren** [comment]
Unfortunately a category is a must, since Frilans Finans requires it. The list they use come from http://www.scb.se/sv_/Dokumentation/Klassifikationer-och-standarder/Standard-for-svensk-yrkesklassificering-SSYK/.

**Comment by camillaryd** [comment]
Okay. I understand their requirement, and if we would ad another category it would mess up the stats. But I think we should watch this issue if we have don't have the same jobs they usually administrate.

**Comment by buren** [comment]
@camillaryd I totally agree 👍 
Its one of the things we should discuss with them.. currently the category list is far from being user friendly as we've discussed previously.. the number of categories are just ridiculous (~8200!).
