### ISSUE TITLE
Update copy on start page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#693]
**Thank you Johanna Thorell** for contributing these texts!

---

Matching newly arrived immigrants with vacant jobs in Sweden

Employ a newly arrived candidate
Click here to create a new job

Find a job in Sweden
Click here for available jobs

New jobs
Show all jobs

For employers
Upload a vacant job
Choose a candidate
Pay only when the job has been completed
Create a job

For employees
Search for vacant jobs near you
Do the work
Get paid within two weeks
Find a job

How to apply
To apply for a job you need:
Co-ordination number or personal ID number
Access to a bank account
Work permit
Apply for your first job

**Comment by camillaryd** [comment]
Hold on with this one before we set the whole copy work sheet. :)
