### ISSUE TITLE
Update copy on about page [draft]

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#694]
**Thank you Johanna Thorell** for contributing these texts!

---

Just Arrived enables employers to post vacant jobs and applicants to find jobs and apply for them. Our goal is to specifically help newly arrived immigrants to enter the Swedish job market. We are owned by a foundation. Our partners are an association of companies and much of our work is done pro bono.

**Comment by camillaryd** [comment]
I've added this one to the excel copy sheet.
