### ISSUE TITLE
Explain "Titel" in the context of creating a job

### ISSUE THREAD

**Issue by camillaryd** [justarrived/just-match-frontend#697]
__Description__

When you create a job we ask the user to state Titel (Titel which will be shown of the page) and "Category" as in the working titel of the person you are looking for. As a new user who just signed up, you wonder if this is my own titel or the person that I'm looking for. Can we a better explanation here, for the whole form or the field?

__Severity__:

* Can perform without problem but looks wrong

**Comment by buren** [comment]
@camillaryd I agree.

I've think that we should add another field called `Short description` that can't be longer than ~140 characters. Then we could use that field when listing jobs.

__Screenshot__:

<img width="699" alt="screen shot 2016-07-13 at 17 32 56" src="https://cloud.githubusercontent.com/assets/922411/16809249/e56adac0-491f-11e6-8773-eb3c1f4b0275.png">

**Comment by pstenstrm** [comment]
Would it be enough to truncate the text in the listing?

**Comment by buren** [comment]
@pstenstrm both yes and no imo. 

Truncation would potentially not be a good short summary of the job. On the other hand it's more work for user to fill it out. Maybe have it as an optional field and fallback on truncation?

**Comment by pstenstrm** [comment]
Having an optional short summary and falling back to truncating the description sounds good to me.

**Comment by buren** [comment]
@pstenstrm added `short-description` to the [API](https://api.justarrived.se/api_docs/1.0/jobs/show.html).

**Comment by buren** [comment]
Reading the original description, my comment really didn't address it.. I must have mixed this issue up when another. Any way I've created a new issue based on the discussion between me and @pstenstrm. See #710. 

As for the issue that @camillaryd raised in this issue description I created a new "clean" issue #71 and will close this one.
