### ISSUE TITLE
Go over the copy for the confirmation messages from applying to confirm the job been done.

### ISSUE THREAD

**Issue by camillaryd** [justarrived/just-match-frontend#701]
We need a copy to go over the short confirmation and instructional messages in the app from Applying for a job
Accept to perform a job
Confirm the job has been done

Sent offer to an applicant
Confirm the job has been done
Giving a recommendation.

**Comment by buren** [comment]
@camillaryd lets go through this during our next meeting :)

**Comment by camillaryd** [comment]
I think this is a great task for Johanna :)

**Comment by buren** [comment]
:+1:

**Comment by camillaryd** [comment]
They are all in the copy work sheet!
