### ISSUE TITLE
Refresh rate in private messaging

### ISSUE THREAD

**Issue by camillaryd** [justarrived/just-match-frontend#706]
__Description__

Short description of the problem

Not sure if this wouldn't be a problem in production, but there has to be a refresh rate in the messaging so you don't have to refresh the browser to see a new message. Brings me back to 1997 and passagen chat..:)

__Severity__:

* Can perform with problem
* New feature / suggestion

**Comment by pstenstrm** [comment]
I think this is the same issue as #603

**Comment by buren** [comment]
Yes you're right @pstenstrm, this is a duplicate of #603. Closing this.

Thank you @camillaryd for reporting this! ❤️
