### ISSUE TITLE
Doesn't redirect to login page if token expires

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#708]
__Description__

The Auth tokens can expire and therefore the frontend should re-direct to the login page if the auth token stops to work. Currently you have to manually click "Log out" and then "Login".

__Severity__: Can not perform action

__How to recreate it__

This bug is kinda tricky to reproduce, since you'll need to simulate that the token expires. The only way of doing that is using the admin interface.

1. Login in as any user
2. In another tab goto `/admin`
3. Goto "Tokens" (left side menu)
4. Find the users auth token and click "Edit"
5. Edit `Expires on` to be in the passed
6. Go back to the other browser tab and make a request that requires authentication, such as "My Jobs"

__What happend__

No resources or error messages are displayed in the UI.

__Expected outcome__

A redirect to the login page with a message like "Your login session has expired, please login again.".

**Comment by pstenstrm** [comment]
I think this is a must have. I think the state the user finds themself in now is very confusing and might cause us to lose a lot of frustrated users.

**Comment by pstenstrm** [comment]
I'm having some issues that I think is related to this fix. I can not view the startpage, register-page or any other public facing page and are always redirected to the login-page.

I think this should only happen when I have an expired auth token and it should only happen once. The expired token should be removed.

**Comment by pstenstrm** [comment]
Looking closer into I realise this fix is not the issue. All requests to ´just-match-api-staging.herokuapp.com´ from ´localhost´ when not signed in is met with a 401 response, except for ´/api/v1/languages?filter[system_language]=true´. 

Closing this again
