### ISSUE TITLE
Add Job short description

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#710]
The API has gotten support for a new Job attribute `short-description`.

1. We need to add that to the jobs form as an optional field. Also we should add a description stating where it will be used (in jobs listings view). 

2. In the jobs listings view we should either display `short-description` OR `description` truncated to ~140 characters.

This issue is extracted out of a discussion in https://github.com/justarrived/just-match-frontend/issues/697.

**Comment by buren** [comment]
@camillaryd how many characters do you think should be the maximum in the job listings view?

**Comment by pstenstrm** [comment]
What's still missing for this issue is a text explaining what the short description is for. 

Do we have other examples of info texts for inputs?

**Comment by buren** [comment]
@pstenstrm unfortunately we don't have that many (any?) places where the an input field has "help text"/hint. The simplest might be just to have it displayed underneath, were error messages is displayed (and if both are present have the validation error be displayed above the hint).
