### ISSUE TITLE
Explain "Titel" in the context of creating a job 

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#711]
> Original: @camillaryd: https://github.com/justarrived/just-match-frontend/issues/697#issue-165290751
>
> __Description__
> 
> When you create a job we ask the user to state Titel (Titel which will be shown of the page) and > "Category" as in the working titel of the person you are looking for. As a new user who just signed up, you wonder if this is my own titel or the person that I'm looking for. Can we a better explanation here, for the whole form or the field?
> 
> __Severity__:
> 
> * Can perform without problem but looks wrong

**Comment by camillaryd** [comment]
We'll call it "short description" ! I'm adding this one to the work sheet.
