### ISSUE TITLE
Rename dark selector to secondary

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#712]
As mentioned in https://github.com/justarrived/just-match-frontend/pull/705#issuecomment-233182776. 

We should change all occurrences of the `dark` with `secondary`. We might change the colour in the future and at that point we should only have to edit the css for the `.secondary` selector, rather than changing the selector itself..

**Comment by pstenstrm** [comment]
Looking closer at the classes and specifically buttons, there's a very wide range ways buttons have been created. We have the `.button` class, which used to have the `.dark` variant. Then we also have the bootstrap style `.btn` with `.btn-pos` and `.btn-neg` variations. And lastly we have the buttons that are styled on elements or pseudo-selectors like `:first-child` and so on. 

To make the site easier to contribute to in the future we should align things like this.

**Comment by buren** [comment]
@pstenstrm couldn't agree more. This also makes refactoring harder. I'll open an issue for this and close this since this particular issue is fixed.
