### ISSUE TITLE
Title is not shown on job approval page

### ISSUE THREAD

**Issue by pstenstrm** [justarrived/just-match-frontend#720]
__Description__

When creating a new job and continuing to the approval page the title of the job is not shown.

__Severity__:

* Can perform with problem

__URL__: #/job/approve

__Role__: Company user

__How to recreate it__

1. Goto: http://justarrived.dev-machine.com/#
2. Log in as company user
3. Click "menu"
4. Click "Create job"
5. Fill the form 
6. Click "Next step"

__What happend__
Job Title is not shown

__Expected outcome__
I should be able to preview the job Title

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome 51

__Screenshot__
<img width="1081" alt="screen shot 2016-07-25 at 13 35 12" src="https://cloud.githubusercontent.com/assets/1674417/17100430/99ecead6-526e-11e6-9c04-eb76c08abc55.png">

**Comment by camillaryd** [comment]
Yes, It should be (titel= short description) and category (= role) in the preview.
