### ISSUE TITLE
Category is lost when editing job

### ISSUE THREAD

**Issue by pstenstrm** [justarrived/just-match-frontend#721]
__Description__

When reviewing a new job and going back to edit it the value for Category is not filled.

__Severity__:

* Can perform with problem

__URL__: #/job/create

__Role__: Company user

__How to recreate it__

1. Goto: http://justarrived.dev-machine.com/#
2. Log in as company user
3. Click "menu"
4. Click "Create job"
5. Fill the form 
6. Click "Next step"
7. Click "Edit"

__What happend__
Category is not filled

__Expected outcome__
Category should be filled with the previously selected value

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome 51

**Comment by buren** [comment]
@pstenstrm :+1: thank you, fixing things like this is what makes the difference between an ok app and a great one :heart:
