### ISSUE TITLE
Normalise button css

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#724]
@pstenstrm https://github.com/justarrived/just-match-frontend/issues/712#issuecomment-234937748:

Looking closer at the classes and specifically buttons, there's a very wide range ways buttons have been created. We have the `.button` class, which used to have the `.dark` variant. Then we also have the bootstrap style `.btn` with `.btn-pos` and `.btn-neg` variations. And lastly we have the buttons that are styled on elements or pseudo-selectors like `:first-child` and so on. 

To make the site easier to contribute to in the future we should align things like this. 

---

**Comment by buren** [comment]
@pstenstrm do you have any opinions/suggestions on which of the styles we should keep?

**Comment by pstenstrm** [comment]
I think simplicity always wins. `.button` is as simple and easy to understand as it gets. 

I don't think we actually use much of what's in the bootstrap library.

**Comment by buren** [comment]
It would be interesting to completely remove bootstrap, keep `normalize.css` and see how much is needed to be fixed. Maybe we could remove the dependency on Bootstrap all together.

**Comment by buren** [comment]
@pstenstrm lets try to extract those properties out then 🔪 Bootstrap 🚀

**Comment by pstenstrm** [comment]
This has some dependency on #684
