### ISSUE TITLE
No way to edit user details on some screen sizes

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#751]
__Description__

Currently there is no way to update user details since the sidebar/pane collapses as soon as anything is clicked (no JavaScript error is thrown..).

__Severity__:

Can not perform action ❗ 

__URL__: *

__Error message__: No error message is thrown in the console..

__Role__: *

__How to recreate it__

1. Login
2. Click "Menu"
3. Click the "gear"-icon
4. Click "Edit"/"Personal details"/"Bank details" (they all don't work...)

__What happend__

The sidebar/pane closes..

__Browser : Present on at least Chrome and Firefox (but probably the rest too..)

**Comment by pstenstrm** [comment]
I can not reproduce the error. I've tried the latest Chrome and Firefox on OSX and Windows 10 and the latest Edge.

I expected this would be something related to #670.

**Comment by buren** [comment]
@pstenstrm thank you for checking! I reopened the issue and will try to find stable reproduction steps :)

**Comment by buren** [comment]
See #670
