### ISSUE TITLE
Email validation rejects valid email addresses

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#93]
__Description__

Even though the email address is valid the frontend marks it as invalid and its not possible to submit the user registration form.

__Severity__: Can't complete action

__URL__

http://justarrived.dev-machine.com/#/user/register

__Error message__: "Du måste ange en giltig email"

__Role__: Not logged in

__How to recreate it__

1. Goto [register user page](http://justarrived.dev-machine.com/#/user/register)
2. Fill in the email address `somename+1@example.com`
3. The frontend marks it as an invalid email even though its not

__Expected outcome__

No validation error and possible to submit form.

__System__: OSX

__Browser ([check what browser am I running](https://whatbrowser.org))__: Chrome

__Screenshot__

<img width="529" alt="screen shot 2016-05-04 at 09 10 06" src="https://cloud.githubusercontent.com/assets/922411/15007310/2261303e-11d8-11e6-90ae-3f801fb8d84e.png">

**Comment by ti-sedp** [comment]
Add more ng-patter follow w3c standard

w3c email description and regular expression
http://w3c.github.io/html-reference/input.email.html

**Comment by buren** [comment]
@ti-sedp I'm not sure that I follow. Do you mean that its the default Angular email validator that rejects the above email and that that follows the W3C email reg ex "standard"?

The email address above is a valid email and not totally uncommon for Gmail users to use that format (personally I use it a lot..).

Re-opening this, since its a valid email and it should be possible to use this format.

**Comment by buren** [comment]
Sorry @ti-sedp this is has been fixed (I was testing against the wrong version....)
